stages:
  - prod-build
  - prod-deploy
  - prod-notification
# - deploy


prod-build:
  stage: prod-build
  script:
    - docker build -t prod_admin_image$CI_COMMIT_SHA -f DockerfileProd .
  tags:
    - prod-admin
  only:
    - master

prod-deploy:
  stage: prod-deploy
  script:
    - docker run -it -d --name prod-admin prod_admin_image$CI_COMMIT_SHA
    - docker cp prod-admin:/usr/src/app/build /home/gitlab-runner/prod-admin/
    - docker rm -f prod-admin
  tags:
    - prod-admin
  only:
    - master

prod-notification-pass:
  stage: prod-notification
  script:
    - curl -s
      "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
      -F chat_id=${TELEGRAM_CHAT_ID}
      -F text='🟢 UBAdmin Production Deployed Successfully !'
  tags:
    - prod-admin
  only:
    - master
  when: on_success

prod-notification-fail:
  stage: prod-notification
  script:
    - curl -s
      "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
      -F chat_id=${TELEGRAM_CHAT_ID}
      -F text='🔴 UBAdmin Production Deploy Failed !'
  tags:
    - prod-admin
  only:
    - master
  when: on_failure

#deploy:
#  before_script:
#  stage: deploy
#  tags:
#    - shell
#  script:
#    - ssh -p ${DEPLOY_SSH_PORT} -T ${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST} "cd /home/exchange/new-ub-admin/ && git checkout master && git pull origin master && exit"
#  only:
#    - master
#  when: manual
