/*
 *
 * FundsPage constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = 'app/FundsPage/DEFAULT_ACTION',
  GET_BALANCE_PAGE_DATA_ACTION = 'app/FundsPage/GET_BALANCE_PAGE_DATA_ACTION',
  SET_BALANCE_PAGE_DATA_ACTION = 'app/FundsPage/SET_BALANCE_PAGE_DATA_ACTION',
  SET_IS_LOADING_BALANCE_PAGE_DATA_ACTION = 'app/FundsPage/SET_IS_LOADING_BALANCE_PAGE_DATA_ACTION',

  GET_TRANSACTION_HISTORY_PAGE_DATA_ACTION = 'app/FundsPage/GET_TRANSACTION_HISTORY_PAGE_DATA_ACTION',
  SET_TRANSACTION_HISTORY_PAGE_DATA_ACTION = 'app/FundsPage/SET_TRANSACTION_HISTORY_PAGE_DATA_ACTION',
  SET_IS_LOADING_TRANSACTION_HISTORY_PAGE_DATA_ACTION = 'app/FundsPage/SET_IS_LOADING_TRANSACTION_HISTORY_PAGE_DATA_ACTION',

  GET_DEPOSITE_AND_WITHDRAWS_DATA_ACTION = 'app/FundsPage/GET_DEPOSITE_AND_WITHDRAWS_DATA_ACTION',
  SET_USER_DATA_ACTION = 'app/FundsPage/SET_USER_DATA_ACTION',
  GET_USER_DATA_ACTION = 'app/FundsPage/GET_USER_DATA_ACTION',
  GET_RAW_DEPOSITE_AND_WITHDRAWS_DATA_ACTION = 'app/FundsPage/GET_RAW_DEPOSITE_AND_WITHDRAWS_DATA_ACTION',
  SET_DEPOSITE_AND_WITHDRAWS_DATA_ACTION = 'app/FundsPage/SET_DEPOSITE_AND_WITHDRAWS_DATA_ACTION',
  ADD_WITHDRAWS_DATA_ACTION = 'app/FundsPage/ADD_WITHDRAWS_DATA_ACTION',

  SET_IS_LOADING_DEPOSITE_AND_WITHDRAWS_DATA_ACTION = 'app/FundsPage/SET_IS_LOADING_DEPOSITE_AND_WITHDRAWS_DATA_ACTION',

  GET_PAYMENT_DETAIL_ACTION = 'app/FundsPage/GET_PAYMENT_DETAIL_ACTION',
  SET_PAYMENT_DETAIL_ACTION = 'app/FundsPage/SET_PAYMENT_DETAIL_ACTION',
  ADD_NEW_ADDRESS_ACTION = 'app/FundsPage/ADD_NEW_ADDRESS_ACTION',

  GET_FORMER_WITHDRAW_ADDRESSES = 'app/OrdersPage/GET_FORMER_WITHDRAW_ADDRESSES',
  SET_FORMER_WITHDRAW_ADDRESSES = 'app/OrdersPage/SET_FORMER_WITHDRAW_ADDRESSES',
  ADD_FORMER_WITHDRAW_ADDRESSES = 'app/OrdersPage/ADD_FORMER_WITHDRAW_ADDRESSES',
  WITHDRAW_ACTION = 'app/OrdersPage/WITHDRAW_ACTION',
  PRE_WITHDRAW_ACTION = 'app/OrdersPage/PRE_WITHDRAW_ACTION',
  GET_INFINITE_DW_ACTION = 'app/OrdersPage/GET_INFINITE_DW_ACTION',
}
enum FundsPages {
  BALANCE = 'Balance',
  DEPOSIT = 'Deposit',
  WITHDRAWALS = 'Withdrawals',
  TRANSACTION_HISTORY = 'TransactionHistory',
}
export enum DWStatus {
  IN_PROGRESS = 'in progress',
  PENDING = 'pending',
  Completed = 'filled',
  Complete = 'completed',
  CONFIRMED = 'confirmed',
  Canceled = 'canceled',
  Cancel = 'canceled',
  Rejected = 'rejected',
  Expired = 'expired',
}
export default ActionTypes;
export { FundsPages };
