import { LayoutNames } from 'components/AppHeader/constants';
import { LocalStorageKeys } from 'services/constants';
export enum LayoutContainers {
  TRADEHEADER = 'TRADEHEADER',
  MARKETWATCH = 'MARKETWATCH',
  MARKETTRADE = 'MARKETTRADE',
  ORDERBOOK = 'ORDERBOOK',
  ORDERS = 'ORDERS',
  TRADECHART = 'TRADECHART',
  NEWORDER = 'NEWORDER',
}
export const sizes = {
  defaultLargeScreen: [
    {
      i: LayoutContainers.TRADEHEADER,
      x: 0,
      y: 0,
      w: 40,
      h: 4,
      minW: 40,
      maxW: 48,
      minH: 4,
      maxH: 4,
    },
    {
      i: LayoutContainers.MARKETWATCH,
      x: 40,
      y: 0,
      w: 8,
      h: 20,
      minW: 8,
      maxW: 12,
      minH: 12,
      maxH: 40,
    },
    {
      i: LayoutContainers.MARKETTRADE,
      x: 0,
      y: 14,
      w: 8,
      h: 15,
      minW: 8,
      maxW: 12,
      minH: 8,
      maxH: 40,
    },
    {
      i: LayoutContainers.ORDERBOOK,
      x: 8,
      y: 14,
      w: 32,
      h: 15,
      minW: 20,
      maxW: 48,
      minH: 8,
      maxH: 50,
    },
    {
      i: LayoutContainers.NEWORDER,
      x: 40,
      y: 12,
      w: 8,
      h: 38,
      minW: 8,
      maxW: 16,
      minH: 32,
      maxH: 38,
    },
    {
      i: LayoutContainers.ORDERS,
      x: 0,
      y: 20,
      w: 40,
      h: 15,
      minW: 24,
      maxW: 48,
      minH: 15,
      maxH: 60,
    },
    {
      i: LayoutContainers.TRADECHART,
      x: 0,
      y: 4,
      w: 40,
      h: 24,
      minW: 32,
      maxW: 48,
      minH: 12,
      maxH: 60,
    },
  ],
  defaultSmallScreen: [
    {
      i: LayoutContainers.TRADEHEADER,
      x: 0,
      y: 0,
      w: 37,
      h: 4,
      minW: 36,
      maxW: 48,
      minH: 4,
      maxH: 4,
    },
    {
      i: LayoutContainers.MARKETWATCH,
      x: 40,
      y: 0,
      w: 11,
      h: 17,
      minW: 11,
      maxW: 16,
      minH: 17,
      maxH: 40,
    },
    {
      i: LayoutContainers.MARKETTRADE,
      x: 0,
      y: 14,
      w: 10,
      h: 17,
      minW: 10,
      maxW: 12,
      minH: 8,
      maxH: 40,
    },
    {
      i: LayoutContainers.ORDERBOOK,
      x: 10,
      y: 14,
      w: 27,
      h: 17,
      minW: 20,
      maxW: 48,
      minH: 8,
      maxH: 50,
    },
    {
      i: LayoutContainers.NEWORDER,
      x: 40,
      y: 12,
      w: 11,
      h: 41,
      minW: 11,
      maxW: 11,
      minH: 41,
      maxH: 41,
    },
    {
      i: LayoutContainers.ORDERS,
      x: 0,
      y: 20,
      w: 37,
      h: 15,
      minW: 24,
      maxW: 48,
      minH: 15,
      maxH: 60,
    },
    {
      i: LayoutContainers.TRADECHART,
      x: 0,
      y: 4,
      w: 37,
      h: 22,
      minW: 32,
      maxW: 48,
      minH: 18,
      maxH: 60,
    },
  ],
  chartLargeScreen: [
    {
      i: LayoutContainers.TRADEHEADER,
      x: 0,
      y: 0,
      w: 40,
      h: 4,
      minW: 40,
      maxW: 48,
      minH: 4,
      maxH: 4,
    },
    {
      i: LayoutContainers.MARKETWATCH,
      x: 40,
      y: 0,
      w: 8,
      h: 21,
      minW: 8,
      maxW: 12,
      minH: 12,
      maxH: 40,
    },
    {
      i: LayoutContainers.MARKETTRADE,
      x: 0,
      y: 0,
      w: 0,
      h: 0,
      minW: 0,
      maxW: 0,
      minH: 0,
      maxH: 0,
    },
    {
      i: LayoutContainers.ORDERBOOK,
      x: 0,
      y: 0,
      w: 0,
      h: 0,
      minW: 0,
      maxW: 0,
      minH: 0,
      maxH: 0,
    },
    {
      i: LayoutContainers.NEWORDER,
      x: 40,
      y: 12,
      w: 8,
      h: 37,
      minW: 8,
      maxW: 16,
      minH: 32,
      maxH: 38,
    },
    {
      i: LayoutContainers.ORDERS,
      x: 0,
      y: 20,
      w: 40,
      h: 19,
      minW: 24,
      maxW: 48,
      minH: 14,
      maxH: 60,
    },
    {
      i: LayoutContainers.TRADECHART,
      x: 0,
      y: 4,
      w: 40,
      h: 35,
      minW: 32,
      maxW: 48,
      minH: 20,
      maxH: 60,
    },
  ],
  chartSmallScreen: [
    {
      i: LayoutContainers.TRADEHEADER,
      x: 0,
      y: 0,
      w: 36,
      h: 4,
      minW: 36,
      maxW: 48,
      minH: 4,
      maxH: 4,
    },
    {
      i: LayoutContainers.MARKETWATCH,
      x: 40,
      y: 0,
      w: 12,
      h: 16,
      minW: 12,
      maxW: 16,
      minH: 11,
      maxH: 40,
    },
    {
      i: LayoutContainers.MARKETTRADE,
      x: 0,
      y: 0,
      w: 0,
      h: 0,
      minW: 0,
      maxW: 0,
      minH: 0,
      maxH: 0,
    },
    {
      i: LayoutContainers.ORDERBOOK,
      x: 0,
      y: 0,
      w: 0,
      h: 0,
      minW: 0,
      maxW: 0,
      minH: 0,
      maxH: 0,
    },
    {
      i: LayoutContainers.NEWORDER,
      x: 40,
      y: 12,
      w: 12,
      h: 41,
      minW: 12,
      maxW: 16,
      minH: 41,
      maxH: 41,
    },
    {
      i: LayoutContainers.ORDERS,
      x: 0,
      y: 20,
      w: 36,
      h: 20,
      minW: 24,
      maxW: 48,
      minH: 14,
      maxH: 60,
    },
    {
      i: LayoutContainers.TRADECHART,
      x: 0,
      y: 4,
      w: 36,
      h: 33,
      minW: 32,
      maxW: 48,
      minH: 20,
      maxH: 60,
    },
  ],
};
export const bigScreenBreakPoint = 1600;
export const defaultLayout = () => {
  if (window.innerWidth >= bigScreenBreakPoint) {
    return sizes.defaultLargeScreen;
  } else if (window.innerWidth < bigScreenBreakPoint) {
    return sizes.defaultSmallScreen;
  }
  return sizes.defaultLargeScreen;
};
export const chartLayout = () => {
  if (window.innerWidth >= bigScreenBreakPoint) {
    return sizes.chartLargeScreen;
  } else if (window.innerWidth < bigScreenBreakPoint) {
    return sizes.chartSmallScreen;
  }
  return sizes.chartLargeScreen;
};
export const layout = (name?: string) => {
  if (!name || name === LayoutNames.DEFAULT) {
    return defaultLayout();
  } else if (name === LayoutNames.CHART) {
    return chartLayout();
  } else if (name === LayoutNames.CUSTOM) {
    return localStorage[LocalStorageKeys.TRADELAYOUT]
      ? JSON.parse(localStorage[LocalStorageKeys.TRADELAYOUT])
      : defaultLayout();
  }

  return sizes.defaultLargeScreen;
};
