FROM golang:1.24
ENV GO111MODULE=on
WORKDIR /app

COPY . .

#complile main
RUN go build -mod=vendor cmd/rabbit-consumer/main.go

#RUN go mod init gitlab.com/majid1370/rabbitmq-consumer

#RUN  go build -mod=vendor

#ENTRYPOINT ["/app/rabbitmq-consumer"]
