/*
 *
 * OrdersPage constants
 *
 */

enum ActionTypes {
	DEFAULT_ACTION='app/OrdersPage/DEFAULT_ACTION',

	GET_OPEN_ORDERS_ACTION='app/OrdersPage/GET_OPEN_ORDERS_ACTION',
	SET_OPEN_ORDERS_ACTION='app/OrdersPage/SET_OPEN_ORDERS_ACTION',

	GET_ORDER_HISTORY_ACTION='app/OrdersPage/GET_ORDER_HISTORY_ACTION',
	GET_PAGINATED_ORDER_HISTORY_ACTION='app/OrdersPage/GET_PAGINATED_ORDER_HISTORY_ACTION',
	GET_PAGINATED_TRADE_HISTORY_ACTION='app/OrdersPage/GET_PAGINATED_TRADE_HISTORY_ACTION',
	//  SET_PAGINATED_ORDER_HISTORY_ACTION = 'app/OrdersPage/SET_PAGINATED_ORDER_HISTORY_ACTION',
	GET_FILTERED_ORDER_HISTORY_ACTION='app/OrdersPage/GET_FILTERED_ORDER_HISTORY_ACTION',
	SET_ORDER_HISTORY_ACTION='app/OrdersPage/SET_ORDER_HISTORY_ACTION',

	GET_TRADE_HISTORY_ACTION='app/OrdersPage/GET_TRADE_HISTORY_ACTION',
	SET_TRADE_HISTORY_ACTION='app/OrdersPage/SET_TRADE_HISTORY_ACTION',

	SET_IS_LOADING_OPEN_ORDERS_ACTION='app/OrdersPage/SET_IS_LOADING_OPEN_ORDERS_ACTION',
	SET_IS_LOADING_ORDER_HISTORY_ACTION='app/OrdersPage/SET_IS_LOADING_ORDER_HISTORY_ACTION',
	SET_IS_LOADING_TRADE_HISTORY_ACTION='app/OrdersPage/SET_IS_LOADING_TRADE_HISTORY_ACTION',

	SET_CURRENCIES='app/OrdersPage/SET_CURRENCIES',

	GET_PAYMENT_DETAIL_ACTION='app/OrdersPage/GET_PAYMENT_DETAIL_ACTION',
	SET_PAYMENT_DETAIL_ACTION='app/OrdersPage/SET_PAYMENT_DETAIL_ACTION',

	////trade new order
	GET_CURRENCY_PAIR_INFO='app/TradePage/GET_CURRENCY_PAIR_INFO',
	CREATE_NEW_ORDER_ACTION='app/TradePage/CREATE_NEW_ORDER_ACTION',
	CANCEL_ORDER_ACTION='app/TradePage/CANCEL_ORDER_ACTION',
	ADD_NEW_ORDER_ACTION='app/TradePage/ADD_NEW_ORDER_ACTION',
	REFRESH_VISIBLE_ORDER_SECTION='app/TradePage/REFRESH_VISIBLE_ORDER_SECTION',
}
enum OrderPages {
	OPEN_ORDER='openOrder',
	ORDER_HISTORY='orderHistory',
	TRADE_HISTORY='tradeHistory',
}
enum StreamOrderStatus {
	Open='open',
	Filled='filled',
}
export enum BS {
	buy='buy',
	sell='sell',
}
export enum LMS {
	Limit='limit',
	Market='market',
	StopLimit='stop_limit',
}

export default ActionTypes;
export {OrderPages,StreamOrderStatus};
