[program:depth-stream]
command= bash -c "sleep 3 && ./ws depth"
numprocs=1
autostart=true
autorestart=true
startsecs=5
startretries=10
redirect_stderr=false
#stdout_logfile=/home/exchange/project/var/logs/commands/kline-publisher-out.log
#stdout_capture_maxbytes=10MB
#stderr_logfile=/home/exchange/project/var/logs/commands/kline-publisher-err.log
#stderr_capture_maxbytes=10MB


[program:ticker-trade-stream]
command= ./ws ticker trade
numprocs=1
autostart=true
autorestart=true
startsecs=5
startretries=10
redirect_stderr=false
#stdout_logfile=/home/exchange/project/var/logs/commands/kline-publisher-out.log
#stdout_capture_maxbytes=10MB
#stderr_logfile=/home/exchange/project/var/logs/commands/kline-publisher-err.log
#stderr_capture_maxbytes=10MB


[program:kline-stream]
command= ./ws kline_1m kline_5m kline_1h kline_1d
numprocs=1
autostart=true
autorestart=true
startsecs=5
startretries=10
redirect_stderr=false
#stdout_logfile=/home/exchange/project/var/logs/commands/kline-publisher-out.log
#stdout_capture_maxbytes=10MB
#stderr_logfile=/home/exchange/project/var/logs/commands/kline-publisher-err.log
#stderr_capture_maxbytes=10MB