// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
)

// AdminOrderManager is an autogenerated mock type for the AdminOrderManager type
type AdminOrderManager struct {
	mock.Mock
}

// TryToFulfillOrder provides a mock function with given fields: o
func (_m *AdminOrderManager) TryToFulfillOrder(o order.Order) error {
	ret := _m.Called(o)

	var r0 error
	if rf, ok := ret.Get(0).(func(order.Order) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
