// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	configuration "exchange-go/internal/configuration"

	mock "github.com/stretchr/testify/mock"
)

// AppVersionRepository is an autogenerated mock type for the AppVersionRepository type
type AppVersionRepository struct {
	mock.Mock
}

// FindNewAppVersion provides a mock function with given fields: platform, versionCode, appVersion
func (_m *AppVersionRepository) FindNewAppVersion(platform string, versionCode float64, appVersion *configuration.AppVersion) error {
	ret := _m.Called(platform, versionCode, appVersion)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, *configuration.AppVersion) error); ok {
		r0 = rf(platform, versionCode, appVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindNewAppVersions provides a mock function with given fields: platform, versionCode
func (_m *AppVersionRepository) FindNewAppVersions(platform string, versionCode float64) ([]configuration.AppVersion, error) {
	ret := _m.Called(platform, versionCode)

	var r0 []configuration.AppVersion
	if rf, ok := ret.Get(0).(func(string, float64) []configuration.AppVersion); ok {
		r0 = rf(platform, versionCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]configuration.AppVersion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(platform, versionCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
