// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	auth "exchange-go/internal/auth"

	mock "github.com/stretchr/testify/mock"

	response "exchange-go/internal/response"

	user "exchange-go/internal/user"
)

// AuthService is an autogenerated mock type for the Service type
type AuthService struct {
	mock.Mock
}

// ForgotPassword provides a mock function with given fields: params
func (_m *AuthService) ForgotPassword(params auth.ForgotPasswordParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(auth.ForgotPasswordParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(auth.ForgotPasswordParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// ForgotPasswordUpdate provides a mock function with given fields: params
func (_m *AuthService) ForgotPasswordUpdate(params auth.ForgotPasswordUpdateParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(auth.ForgotPasswordUpdateParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(auth.ForgotPasswordUpdateParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetAdminUser provides a mock function with given fields: token
func (_m *AuthService) GetAdminUser(token string) (*user.User, error) {
	ret := _m.Called(token)

	var r0 *user.User
	if rf, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenByRefreshToken provides a mock function with given fields: params
func (_m *AuthService) GetTokenByRefreshToken(params auth.GetTokenByRefreshTokenParams) (interface{}, int) {
	ret := _m.Called(params)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(auth.GetTokenByRefreshTokenParams) interface{}); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(auth.GetTokenByRefreshTokenParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: token
func (_m *AuthService) GetUser(token string) (*user.User, error) {
	ret := _m.Called(token)

	var r0 *user.User
	if rf, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: params
func (_m *AuthService) Login(params auth.LoginParams) (interface{}, int) {
	ret := _m.Called(params)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(auth.LoginParams) interface{}); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(auth.LoginParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// Register provides a mock function with given fields: params
func (_m *AuthService) Register(params auth.RegisterParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(auth.RegisterParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(auth.RegisterParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// VerifyEmail provides a mock function with given fields: params
func (_m *AuthService) VerifyEmail(params auth.VerifyEmailParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(auth.VerifyEmailParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(auth.VerifyEmailParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}
