// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	auth "exchange-go/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthEventsHandler is an autogenerated mock type for the EventsHandler type
type AuthEventsHandler struct {
	mock.Mock
}

// LogUserLogin provides a mock function with given fields: params
func (_m *AuthEventsHandler) LogUserLogin(params auth.LogUserLoginParams) {
	_m.Called(params)
}

// NotifyIfUserIPHasChanged provides a mock function with given fields: params
func (_m *AuthEventsHandler) NotifyIfUserIPHasChanged(params auth.NotifyIPChangeParams) {
	_m.Called(params)
}
