// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payment "exchange-go/internal/payment"

	mock "github.com/stretchr/testify/mock"

	userbalance "exchange-go/internal/userbalance"
)

// AutoExchangeManager is an autogenerated mock type for the AutoExchangeManager type
type AutoExchangeManager struct {
	mock.Mock
}

// AutoExchange provides a mock function with given fields: p, ub
func (_m *AutoExchangeManager) AutoExchange(p *payment.Payment, ub *userbalance.UserBalance) {
	_m.Called(p, ub)
}
