// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BotAggregationService is an autogenerated mock type for the BotAggregationService type
type BotAggregationService struct {
	mock.Mock
}

//// addToList provides a mock function with given fields: data
//func (_m *BotAggregationService) addToList(data order.botAggregationData) error {
//	ret := _m.Called(data)
//
//	var r0 error
//	if rf, ok := ret.Get(0).(func(order.botAggregationData) error); ok {
//		r0 = rf(data)
//	} else {
//		r0 = ret.Error(0)
//	}
//
//	return r0
//}
