// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	candle "exchange-go/internal/currency/candle"

	mock "github.com/stretchr/testify/mock"
)

// CandleGRPCClient is an autogenerated mock type for the CandleGRPCClient type
type CandleGRPCClient struct {
	mock.Mock
}

// GetAveragePriceOfPairs provides a mock function with given fields: pairNames, fromTime, toTime
func (_m *CandleGRPCClient) GetAveragePriceOfPairs(pairNames []string, fromTime int64, toTime int64) ([]candle.AveragePairPrice, error) {
	ret := _m.Called(pairNames, fromTime, toTime)

	var r0 []candle.AveragePairPrice
	if rf, ok := ret.Get(0).(func([]string, int64, int64) []candle.AveragePairPrice); ok {
		r0 = rf(pairNames, fromTime, toTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]candle.AveragePairPrice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, int64, int64) error); ok {
		r1 = rf(pairNames, fromTime, toTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCandleTrends provides a mock function with given fields: pairNames, timeFrame, fromTime, toTime
func (_m *CandleGRPCClient) GetCandleTrends(pairNames []string, timeFrame string, fromTime int64, toTime int64) ([]candle.CandleTrend, error) {
	ret := _m.Called(pairNames, timeFrame, fromTime, toTime)

	var r0 []candle.CandleTrend
	if rf, ok := ret.Get(0).(func([]string, string, int64, int64) []candle.CandleTrend); ok {
		r0 = rf(pairNames, timeFrame, fromTime, toTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]candle.CandleTrend)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, string, int64, int64) error); ok {
		r1 = rf(pairNames, timeFrame, fromTime, toTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHighAndLowPriceForPairFromDate provides a mock function with given fields: pairName, fromTime
func (_m *CandleGRPCClient) GetHighAndLowPriceForPairFromDate(pairName string, fromTime int64) (candle.HighAndLowPrice, error) {
	ret := _m.Called(pairName, fromTime)

	var r0 candle.HighAndLowPrice
	if rf, ok := ret.Get(0).(func(string, int64) candle.HighAndLowPrice); ok {
		r0 = rf(pairName, fromTime)
	} else {
		r0 = ret.Get(0).(candle.HighAndLowPrice)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(pairName, fromTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastPriceForPair provides a mock function with given fields: pairName, currentTime
func (_m *CandleGRPCClient) GetLastPriceForPair(pairName string, currentTime int64) (string, error) {
	ret := _m.Called(pairName, currentTime)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, int64) string); ok {
		r0 = rf(pairName, currentTime)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(pairName, currentTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
