// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CentrifugoManager is an autogenerated mock type for the CentrifugoManager type
type CentrifugoManager struct {
	mock.Mock
}

// PublishKline provides a mock function with given fields: ctx, pairName, timeFrame, payload
func (_m *CentrifugoManager) PublishKline(ctx context.Context, pairName string, timeFrame string, payload []byte) {
	_m.Called(ctx, pairName, timeFrame, payload)
}

// PublishOrderBook provides a mock function with given fields: ctx, pairName, payload
func (_m *CentrifugoManager) PublishOrderBook(ctx context.Context, pairName string, payload []byte) {
	_m.Called(ctx, pairName, payload)
}

// PublishOrderToOpenOrders provides a mock function with given fields: ctx, privateChannelName, payload
func (_m *CentrifugoManager) PublishOrderToOpenOrders(ctx context.Context, privateChannelName string, payload []byte) {
	_m.Called(ctx, privateChannelName, payload)
}

// PublishPayment provides a mock function with given fields: ctx, privateChannelName, payload
func (_m *CentrifugoManager) PublishPayment(ctx context.Context, privateChannelName string, payload []byte) {
	_m.Called(ctx, privateChannelName, payload)
}

// PublishTicker provides a mock function with given fields: ctx, pairName, payload
func (_m *CentrifugoManager) PublishTicker(ctx context.Context, pairName string, payload []byte) {
	_m.Called(ctx, pairName, payload)
}

// PublishTrades provides a mock function with given fields: ctx, pairName, payload
func (_m *CentrifugoManager) PublishTrades(ctx context.Context, pairName string, payload []byte) {
	_m.Called(ctx, pairName, payload)
}
