// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CentrifugoClient is an autogenerated mock type for the CentrifugoClient type
type CentrifugoClient struct {
	mock.Mock
}

// Publish provides a mock function with given fields: channel, data
func (_m *CentrifugoClient) Publish(channel string, data interface{}) error {
	ret := _m.Called(channel, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(channel, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Broadcast provides a mock function with given fields: channels, data
func (_m *CentrifugoClient) Broadcast(channels []string, data interface{}) error {
	ret := _m.Called(channels, data)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, interface{}) error); ok {
		r0 = rf(channels, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
