// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	communication "exchange-go/internal/communication"

	mock "github.com/stretchr/testify/mock"
)

// CommunicationService is an autogenerated mock type for the Service type
type CommunicationService struct {
	mock.Mock
}

// SendContactUsToAdmin provides a mock function with given fields: adminUser, params
func (_m *CommunicationService) SendContactUsToAdmin(adminUser communication.CommunicatingUser, params communication.ContactUsToAdminParams) {
	_m.Called(adminUser, params)
}

// SendCryptoPaymentStatusUpdateEmail provides a mock function with given fields: u, params
func (_m *CommunicationService) SendCryptoPaymentStatusUpdateEmail(u communication.CommunicatingUser, params communication.CryptoPaymentStatusUpdateEmailParams) {
	_m.Called(u, params)
}

// SendIPChangedEmail provides a mock function with given fields: u, params
func (_m *CommunicationService) SendIPChangedEmail(u communication.CommunicatingUser, params communication.SendIPChangedEmailParams) {
	_m.Called(u, params)
}

// SendPasswordChangedEmail provides a mock function with given fields: u, params
func (_m *CommunicationService) SendPasswordChangedEmail(u communication.CommunicatingUser, params communication.PasswordChangedEmailParams) {
	_m.Called(u, params)
}

// SendUserForgotPasswordEmail provides a mock function with given fields: u, params
func (_m *CommunicationService) SendUserForgotPasswordEmail(u communication.CommunicatingUser, params communication.ForgotPasswordEmailParams) {
	_m.Called(u, params)
}

// SendUserPhoneConfirmationSms provides a mock function with given fields: u, code
func (_m *CommunicationService) SendUserPhoneConfirmationSms(u communication.CommunicatingUser, code string) {
	_m.Called(u, code)
}

// SendVerificationEmailToUser provides a mock function with given fields: u, link
func (_m *CommunicationService) SendVerificationEmailToUser(u communication.CommunicatingUser, link string) {
	_m.Called(u, link)
}

// SendWithdrawConfirmationEmail provides a mock function with given fields: u, coin, amount, address, code
func (_m *CommunicationService) SendWithdrawConfirmationEmail(u communication.CommunicatingUser, coin string, amount string, address string, code string) {
	_m.Called(u, coin, amount, address, code)
}
