// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigurationRepository is an autogenerated mock type for the Repository type
type ConfigurationRepository struct {
	mock.Mock
}
