// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Configs is an autogenerated mock type for the Configs type
type Configs struct {
	mock.Mock
}

// GetActiveExternalExchange provides a mock function with given fields:
func (_m *Configs) GetActiveExternalExchange() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetAndroidRecaptchaSecretKey provides a mock function with given fields:
func (_m *Configs) GetAndroidRecaptchaSecretKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetAndroidRecaptchaSiteKey provides a mock function with given fields:
func (_m *Configs) GetAndroidRecaptchaSiteKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetBool provides a mock function with given fields: name
func (_m *Configs) GetBool(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetDomain provides a mock function with given fields:
func (_m *Configs) GetDomain() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEnv provides a mock function with given fields:
func (_m *Configs) GetEnv() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetImagePath provides a mock function with given fields:
func (_m *Configs) GetImagePath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetInt provides a mock function with given fields: name
func (_m *Configs) GetInt(name string) int {
	ret := _m.Called(name)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetRecaptchaSecretKey provides a mock function with given fields:
func (_m *Configs) GetRecaptchaSecretKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRecaptchaSiteKey provides a mock function with given fields:
func (_m *Configs) GetRecaptchaSiteKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSentryDsn provides a mock function with given fields:
func (_m *Configs) GetSentryDsn() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetString provides a mock function with given fields: name
func (_m *Configs) GetString(name string) string {
	ret := _m.Called(name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetStringSlice provides a mock function with given fields: name
func (_m *Configs) GetStringSlice(name string) []string {
	ret := _m.Called(name)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *Configs) Set(key string, value interface{}) {
	_m.Called(key, value)
}

// UnmarshalKey provides a mock function with given fields: key, i
func (_m *Configs) UnmarshalKey(key string, i interface{}) error {
	ret := _m.Called(key, i)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
