// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	country "exchange-go/internal/country"

	mock "github.com/stretchr/testify/mock"

	response "exchange-go/internal/response"
)

// CountryService is an autogenerated mock type for the Service type
type CountryService struct {
	mock.Mock
}

// GetCountries provides a mock function with given fields:
func (_m *CountryService) GetCountries() (response.APIResponse, int) {
	ret := _m.Called()

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func() response.APIResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetCountryByID provides a mock function with given fields: id
func (_m *CountryService) GetCountryByID(id int64) (country.Country, error) {
	ret := _m.Called(id)

	var r0 country.Country
	if rf, ok := ret.Get(0).(func(int64) country.Country); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(country.Country)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
