// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	country "exchange-go/internal/country"

	mock "github.com/stretchr/testify/mock"
)

// CountryRepository is an autogenerated mock type for the Repository type
type CountryRepository struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *CountryRepository) All(ctx context.Context) []country.Country {
	ret := _m.Called(ctx)

	var r0 []country.Country
	if rf, ok := ret.Get(0).(func(context.Context) []country.Country); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]country.Country)
		}
	}

	return r0
}

// GetCountryByID provides a mock function with given fields: id, _a1
func (_m *CountryRepository) GetCountryByID(id int64, _a1 *country.Country) error {
	ret := _m.Called(id, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *country.Country) error); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
