// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyRepository is an autogenerated mock type for the Repository type
type CurrencyRepository struct {
	mock.Mock
}

// GetActiveCoins provides a mock function with given fields:
func (_m *CurrencyRepository) GetActiveCoins() []currency.Coin {
	ret := _m.Called()

	var r0 []currency.Coin
	if rf, ok := ret.Get(0).(func() []currency.Coin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.Coin)
		}
	}

	return r0
}

// GetCoinByCode provides a mock function with given fields: code, coin
func (_m *CurrencyRepository) GetCoinByCode(code string, coin *currency.Coin) error {
	ret := _m.Called(code, coin)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *currency.Coin) error); ok {
		r0 = rf(code, coin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCoinsAlphabetically provides a mock function with given fields:
func (_m *CurrencyRepository) GetCoinsAlphabetically() []currency.Coin {
	ret := _m.Called()

	var r0 []currency.Coin
	if rf, ok := ret.Get(0).(func() []currency.Coin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.Coin)
		}
	}

	return r0
}
