// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"

	response "exchange-go/internal/response"

	user "exchange-go/internal/user"
)

// CurrencyService is an autogenerated mock type for the Service type
type CurrencyService struct {
	mock.Mock
}

// AddOrRemoveFavoritePair provides a mock function with given fields: u, params
func (_m *CurrencyService) AddOrRemoveFavoritePair(u *user.User, params currency.FavoriteParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, currency.FavoriteParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, currency.FavoriteParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetActiveCoins provides a mock function with given fields:
func (_m *CurrencyService) GetActiveCoins() []currency.Coin {
	ret := _m.Called()

	var r0 []currency.Coin
	if rf, ok := ret.Get(0).(func() []currency.Coin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.Coin)
		}
	}

	return r0
}

// GetActivePairCurrenciesList provides a mock function with given fields:
func (_m *CurrencyService) GetActivePairCurrenciesList() []currency.Pair {
	ret := _m.Called()

	var r0 []currency.Pair
	if rf, ok := ret.Get(0).(func() []currency.Pair); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.Pair)
		}
	}

	return r0
}

// GetCoinByCode provides a mock function with given fields: code
func (_m *CurrencyService) GetCoinByCode(code string) (currency.Coin, error) {
	ret := _m.Called(code)

	var r0 currency.Coin
	if rf, ok := ret.Get(0).(func(string) currency.Coin); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(currency.Coin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrenciesList provides a mock function with given fields:
func (_m *CurrencyService) GetCurrenciesList() (response.APIResponse, int) {
	ret := _m.Called()

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func() response.APIResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetFavoritePairs provides a mock function with given fields: u
func (_m *CurrencyService) GetFavoritePairs(u *user.User) (response.APIResponse, int) {
	ret := _m.Called(u)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User) response.APIResponse); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User) int); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetFees provides a mock function with given fields:
func (_m *CurrencyService) GetFees() (response.APIResponse, int) {
	ret := _m.Called()

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func() response.APIResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetPairByID provides a mock function with given fields: id
func (_m *CurrencyService) GetPairByID(id int64) (currency.Pair, error) {
	ret := _m.Called(id)

	var r0 currency.Pair
	if rf, ok := ret.Get(0).(func(int64) currency.Pair); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(currency.Pair)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPairByName provides a mock function with given fields: name
func (_m *CurrencyService) GetPairByName(name string) (currency.Pair, error) {
	ret := _m.Called(name)

	var r0 currency.Pair
	if rf, ok := ret.Get(0).(func(string) currency.Pair); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(currency.Pair)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPairRatio provides a mock function with given fields: params
func (_m *CurrencyService) GetPairRatio(params currency.GetPairRatioParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(currency.GetPairRatioParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(currency.GetPairRatioParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetPairs provides a mock function with given fields:
func (_m *CurrencyService) GetPairs() (response.APIResponse, int) {
	ret := _m.Called()

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func() response.APIResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetPairsList provides a mock function with given fields:
func (_m *CurrencyService) GetPairsList() (response.APIResponse, int) {
	ret := _m.Called()

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func() response.APIResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetPairsStatistic provides a mock function with given fields: params
func (_m *CurrencyService) GetPairsStatistic(params currency.GetPairsStatisticParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(currency.GetPairsStatisticParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(currency.GetPairsStatisticParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}
