// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	"github.com/stretchr/testify/mock"
)

// CountryRepository is an autogenerated mock type for the Repository type
type Db struct {
	mock.Mock
}

