// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
)

// DecisionManager is an autogenerated mock type for the DecisionManager type
type DecisionManager struct {
	mock.Mock
}

// DecideOrderPlacement provides a mock function with given fields: o
func (_m *DecisionManager) DecideOrderPlacement(o order.Order) (string, error) {
	ret := _m.Called(o)

	var r0 string
	if rf, ok := ret.Get(0).(func(order.Order) string); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(order.Order) error); ok {
		r1 = rf(o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
