// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	engine "exchange-go/internal/engine"

	mock "github.com/stretchr/testify/mock"
)

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// DispatchManually provides a mock function with given fields:
func (_m *Engine) DispatchManually() {
	_m.Called()
}

// HandleInQueueOrders provides a mock function with given fields: pair, price
func (_m *Engine) HandleInQueueOrders(pair string, price string) error {
	ret := _m.Called(pair, price)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(pair, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveOrder provides a mock function with given fields: order
func (_m *Engine) RemoveOrder(order engine.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(engine.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveOrder provides a mock function with given fields: order
func (_m *Engine) RetrieveOrder(order engine.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(engine.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with given fields: workerCount, shouldStartDispatcher
func (_m *Engine) Run(workerCount int, shouldStartDispatcher bool) {
	_m.Called(workerCount, shouldStartDispatcher)
}

// SetPostOrderMatchingCall provides a mock function with given fields: shouldCall
func (_m *Engine) SetPostOrderMatchingCall(shouldCall bool) error {
	ret := _m.Called(shouldCall)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(shouldCall)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Engine) Stop() {
	_m.Called()
}

// SubmitOrder provides a mock function with given fields: order
func (_m *Engine) SubmitOrder(order engine.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(engine.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
