// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
)

// EngineCommunicator is an autogenerated mock type for the EngineCommunicator type
type EngineCommunicator struct {
	mock.Mock
}

// RemoveOrder provides a mock function with given fields: o
func (_m *EngineCommunicator) RemoveOrder(o order.Order) error {
	ret := _m.Called(o)

	var r0 error
	if rf, ok := ret.Get(0).(func(order.Order) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveOrder provides a mock function with given fields: o
func (_m *EngineCommunicator) RetrieveOrder(o order.Order) error {
	ret := _m.Called(o)

	var r0 error
	if rf, ok := ret.Get(0).(func(order.Order) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitOrder provides a mock function with given fields: o
func (_m *EngineCommunicator) SubmitOrder(o order.Order) error {
	ret := _m.Called(o)

	var r0 error
	if rf, ok := ret.Get(0).(func(order.Order) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
