// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	engine "exchange-go/internal/engine"

	mock "github.com/stretchr/testify/mock"
)

// EngineResultHandler is an autogenerated mock type for the EngineResultHandler type
type EngineResultHandler struct {
	mock.Mock
}

// CallBack provides a mock function with given fields: doneOrders, partialOrder
func (_m *EngineResultHandler) CallBack(doneOrders []engine.Order, partialOrder *engine.Order) engine.MatchingResult {
	ret := _m.Called(doneOrders, partialOrder)

	var r0 engine.MatchingResult
	if rf, ok := ret.Get(0).(func([]engine.Order, *engine.Order) engine.MatchingResult); ok {
		r0 = rf(doneOrders, partialOrder)
	} else {
		r0 = ret.Get(0).(engine.MatchingResult)
	}

	return r0
}
