// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	externalexchange "exchange-go/internal/externalexchange"

	mock "github.com/stretchr/testify/mock"
)

// ExternalExchangeOrderRepository is an autogenerated mock type for the OrderRepository type
type ExternalExchangeOrderRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: o
func (_m *ExternalExchangeOrderRepository) Create(o *externalexchange.Order) error {
	ret := _m.Called(o)

	var r0 error
	if rf, ok := ret.Get(0).(func(*externalexchange.Order) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExternalExchangeOrdersLastTradeIds provides a mock function with given fields:
func (_m *ExternalExchangeOrderRepository) GetExternalExchangeOrdersLastTradeIds() []externalexchange.LastTradeIDAndPair {
	ret := _m.Called()

	var r0 []externalexchange.LastTradeIDAndPair
	if rf, ok := ret.Get(0).(func() []externalexchange.LastTradeIDAndPair); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]externalexchange.LastTradeIDAndPair)
		}
	}

	return r0
}

// Update provides a mock function with given fields: o
func (_m *ExternalExchangeOrderRepository) Update(o *externalexchange.Order) error {
	ret := _m.Called(o)

	var r0 error
	if rf, ok := ret.Get(0).(func(*externalexchange.Order) error); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
