// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	externalexchange "exchange-go/internal/externalexchange"

	mock "github.com/stretchr/testify/mock"
)

// ExternalExchangeService is an autogenerated mock type for the Service type
type ExternalExchangeService struct {
	mock.Mock
}

// FetchKlines provides a mock function with given fields: params
func (_m *ExternalExchangeService) FetchKlines(params externalexchange.FetchKlinesParams) ([]externalexchange.FetchKlinesResult, error) {
	ret := _m.Called(params)

	var r0 []externalexchange.FetchKlinesResult
	if rf, ok := ret.Get(0).(func(externalexchange.FetchKlinesParams) []externalexchange.FetchKlinesResult); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]externalexchange.FetchKlinesResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.FetchKlinesParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchOrders provides a mock function with given fields: params
func (_m *ExternalExchangeService) FetchOrders(params externalexchange.FetchOrdersParams) ([]externalexchange.FetchOrdersResult, error) {
	ret := _m.Called(params)

	var r0 []externalexchange.FetchOrdersResult
	if rf, ok := ret.Get(0).(func(externalexchange.FetchOrdersParams) []externalexchange.FetchOrdersResult); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]externalexchange.FetchOrdersResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.FetchOrdersParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchTrades provides a mock function with given fields: params
func (_m *ExternalExchangeService) FetchTrades(params externalexchange.FetchTradesParams) ([]externalexchange.FetchTradesResult, error) {
	ret := _m.Called(params)

	var r0 []externalexchange.FetchTradesResult
	if rf, ok := ret.Get(0).(func(externalexchange.FetchTradesParams) []externalexchange.FetchTradesResult); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]externalexchange.FetchTradesResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.FetchTradesParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchWithdrawals provides a mock function with given fields: params
func (_m *ExternalExchangeService) FetchWithdrawals(params externalexchange.FetchWithdrawalsParams) ([]externalexchange.FetchWithdrawalsResult, error) {
	ret := _m.Called(params)

	var r0 []externalexchange.FetchWithdrawalsResult
	if rf, ok := ret.Get(0).(func(externalexchange.FetchWithdrawalsParams) []externalexchange.FetchWithdrawalsResult); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]externalexchange.FetchWithdrawalsResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.FetchWithdrawalsParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderPlacement provides a mock function with given fields: od
func (_m *ExternalExchangeService) OrderPlacement(od externalexchange.ExternalOrderData) (externalexchange.OrderPlacementResult, error) {
	ret := _m.Called(od)

	var r0 externalexchange.OrderPlacementResult
	if rf, ok := ret.Get(0).(func(externalexchange.ExternalOrderData) externalexchange.OrderPlacementResult); ok {
		r0 = rf(od)
	} else {
		r0 = ret.Get(0).(externalexchange.OrderPlacementResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.ExternalOrderData) error); ok {
		r1 = rf(od)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: params
func (_m *ExternalExchangeService) Withdraw(params externalexchange.WithdrawParams) (externalexchange.WithdrawResult, error) {
	ret := _m.Called(params)

	var r0 externalexchange.WithdrawResult
	if rf, ok := ret.Get(0).(func(externalexchange.WithdrawParams) externalexchange.WithdrawResult); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(externalexchange.WithdrawResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.WithdrawParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
