// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	externalexchange "exchange-go/internal/externalexchange"

	mock "github.com/stretchr/testify/mock"
)

// ExternalExchangeOrderService is an autogenerated mock type for the OrderService type
type ExternalExchangeOrderService struct {
	mock.Mock
}

// CreateExternalExchangeOrderForBot provides a mock function with given fields: o
func (_m *ExternalExchangeOrderService) CreateExternalExchangeOrderForBot(o externalexchange.BotOrderParams) (bool, error) {
	ret := _m.Called(o)

	var r0 bool
	if rf, ok := ret.Get(0).(func(externalexchange.BotOrderParams) bool); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.BotOrderParams) error); ok {
		r1 = rf(o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateExternalExchangeOrderForUser provides a mock function with given fields: o
func (_m *ExternalExchangeOrderService) CreateExternalExchangeOrderForUser(o externalexchange.UserOrderParams) (externalexchange.UserOrderResult, error) {
	ret := _m.Called(o)

	var r0 externalexchange.UserOrderResult
	if rf, ok := ret.Get(0).(func(externalexchange.UserOrderParams) externalexchange.UserOrderResult); ok {
		r0 = rf(o)
	} else {
		r0 = ret.Get(0).(externalexchange.UserOrderResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalexchange.UserOrderParams) error); ok {
		r1 = rf(o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExternalExchangeOrdersLastTradeIds provides a mock function with given fields:
func (_m *ExternalExchangeOrderService) GetExternalExchangeOrdersLastTradeIds() []externalexchange.LastTradeIDAndPair {
	ret := _m.Called()

	var r0 []externalexchange.LastTradeIDAndPair
	if rf, ok := ret.Get(0).(func() []externalexchange.LastTradeIDAndPair); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]externalexchange.LastTradeIDAndPair)
		}
	}

	return r0
}
