// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"
)

// FavoritePairRepository is an autogenerated mock type for the FavoritePairRepository type
type FavoritePairRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: favoritePair
func (_m *FavoritePairRepository) Create(favoritePair *currency.FavoritePair) error {
	ret := _m.Called(favoritePair)

	var r0 error
	if rf, ok := ret.Get(0).(func(*currency.FavoritePair) error); ok {
		r0 = rf(favoritePair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: favoritePair
func (_m *FavoritePairRepository) Delete(favoritePair *currency.FavoritePair) error {
	ret := _m.Called(favoritePair)

	var r0 error
	if rf, ok := ret.Get(0).(func(*currency.FavoritePair) error); ok {
		r0 = rf(favoritePair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFavoritePair provides a mock function with given fields: userId, pairId, favoritePair
func (_m *FavoritePairRepository) GetFavoritePair(userId int, pairId int64, favoritePair *currency.FavoritePair) error {
	ret := _m.Called(userId, pairId, favoritePair)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int64, *currency.FavoritePair) error); ok {
		r0 = rf(userId, pairId, favoritePair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserFavoritePairs provides a mock function with given fields: userId
func (_m *FavoritePairRepository) GetUserFavoritePairs(userId int) []currency.FavoritePairQueryFields {
	ret := _m.Called(userId)

	var r0 []currency.FavoritePairQueryFields
	if rf, ok := ret.Get(0).(func(int) []currency.FavoritePairQueryFields); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.FavoritePairQueryFields)
		}
	}

	return r0
}
