// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ForceTrader is an autogenerated mock type for the ForceTrader type
type ForceTrader struct {
	mock.Mock
}

// GetMinAndMaxPrice provides a mock function with given fields: pairName, orderType, givenPrice
func (_m *ForceTrader) GetMinAndMaxPrice(pairName string, orderType string, givenPrice string) (string, string, error) {
	ret := _m.Called(pairName, orderType, givenPrice)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(pairName, orderType, givenPrice)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string, string, string) string); ok {
		r1 = rf(pairName, orderType, givenPrice)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = rf(pairName, orderType, givenPrice)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ShouldForceTrade provides a mock function with given fields: pairName, orderType, price
func (_m *ForceTrader) ShouldForceTrade(pairName string, orderType string, price string) (bool, error) {
	ret := _m.Called(pairName, orderType, price)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(pairName, orderType, price)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(pairName, orderType, price)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
