// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	"exchange-go/internal/user"
	"github.com/stretchr/testify/mock"
)

// ForgotPasswordManager is an autogenerated mock type for the ForgotPasswordManager type
type ForgotPasswordManager struct {
	mock.Mock
}

// DeleteKey provides a mock function with given fields: u
func (_m *ForgotPasswordManager) DeleteKey(u user.User) error {
	ret := _m.Called(u)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateForgotPasswordAndSendEmail provides a mock function with given fields: u, device, ip
func (_m *ForgotPasswordManager) GenerateForgotPasswordAndSendEmail(u user.User, device string, ip string) error {
	ret := _m.Called(u, device, ip)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.User, string, string) error); ok {
		r0 = rf(u, device, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsCodeCorrect provides a mock function with given fields: u, code
func (_m *ForgotPasswordManager) IsCodeCorrect(u user.User, code string) bool {
	ret := _m.Called(u, code)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.User, string) bool); ok {
		r0 = rf(u, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
