// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	url "net/url"
)

// HttpClient is an autogenerated mock type for the HTTPClient type
type HttpClient struct {
	mock.Mock
}

// HTTPGet provides a mock function with given fields: ctx, _a1, headers
func (_m *HttpClient) HTTPGet(ctx context.Context, _a1 string, headers map[string]string) ([]byte, http.Header, int, error) {
	ret := _m.Called(ctx, _a1, headers)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) []byte); ok {
		r0 = rf(ctx, _a1, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 http.Header
	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) http.Header); ok {
		r1 = rf(ctx, _a1, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(http.Header)
		}
	}

	var r2 int
	if rf, ok := ret.Get(2).(func(context.Context, string, map[string]string) int); ok {
		r2 = rf(ctx, _a1, headers)
	} else {
		r2 = ret.Get(2).(int)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, string, map[string]string) error); ok {
		r3 = rf(ctx, _a1, headers)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// HTTPPost provides a mock function with given fields: ctx, _a1, body, headers
func (_m *HttpClient) HTTPPost(ctx context.Context, _a1 string, body interface{}, headers map[string]string) ([]byte, http.Header, int, error) {
	ret := _m.Called(ctx, _a1, body, headers)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, map[string]string) []byte); ok {
		r0 = rf(ctx, _a1, body, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 http.Header
	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}, map[string]string) http.Header); ok {
		r1 = rf(ctx, _a1, body, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(http.Header)
		}
	}

	var r2 int
	if rf, ok := ret.Get(2).(func(context.Context, string, interface{}, map[string]string) int); ok {
		r2 = rf(ctx, _a1, body, headers)
	} else {
		r2 = ret.Get(2).(int)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, string, interface{}, map[string]string) error); ok {
		r3 = rf(ctx, _a1, body, headers)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// PostForm provides a mock function with given fields: ctx, _a1, data
func (_m *HttpClient) PostForm(ctx context.Context, _a1 string, data url.Values) (*http.Response, error) {
	ret := _m.Called(ctx, _a1, data)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) *http.Response); ok {
		r0 = rf(ctx, _a1, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, url.Values) error); ok {
		r1 = rf(ctx, _a1, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
