// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// InQueueOrderManager is an autogenerated mock type for the InQueueOrderManager type
type InQueueOrderManager struct {
	mock.Mock
}

// HandleInQueueOrders provides a mock function with given fields: ctx, pairName, price
func (_m *InQueueOrderManager) HandleInQueueOrders(ctx context.Context, pairName string, price string) {
	_m.Called(ctx, pairName, price)
	return
}
