// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payment "exchange-go/internal/payment"

	mock "github.com/stretchr/testify/mock"
)

// InternalTransferService is an autogenerated mock type for the InternalTransferService type
type InternalTransferService struct {
	mock.Mock
}

// GetFromExternalInProgressTransfers provides a mock function with given fields:
func (_m *InternalTransferService) GetFromExternalInProgressTransfers() []payment.InternalTransfer {
	ret := _m.Called()

	var r0 []payment.InternalTransfer
	if rf, ok := ret.Get(0).(func() []payment.InternalTransfer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.InternalTransfer)
		}
	}

	return r0
}

// Update provides a mock function with given fields: internalTransfer
func (_m *InternalTransferService) Update(internalTransfer *payment.InternalTransfer) error {
	ret := _m.Called(internalTransfer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*payment.InternalTransfer) error); ok {
		r0 = rf(internalTransfer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *InternalTransferService) UpdateStatus(id int64, status string) error {
	ret := _m.Called(id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
