// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// JwtService is an autogenerated mock type for the JwtService type
type JwtService struct {
	mock.Mock
}

// GetUsernameFromToken provides a mock function with given fields: signedToken
func (_m *JwtService) GetUsernameFromToken(signedToken string) (string, time.Time, error) {
	ret := _m.Called(signedToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(signedToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 time.Time
	if rf, ok := ret.Get(1).(func(string) time.Time); ok {
		r1 = rf(signedToken)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(signedToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IssueToken provides a mock function with given fields: username, userAgent, ip
func (_m *JwtService) IssueToken(username string, userAgent string, ip string) (string, error) {
	ret := _m.Called(username, userAgent, ip)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(username, userAgent, ip)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(username, userAgent, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
