// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	candle "exchange-go/internal/currency/candle"

	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// KlineService is an autogenerated mock type for the KlineService type
type KlineService struct {
	mock.Mock
}

// CreateKlineSync provides a mock function with given fields: params
func (_m *KlineService) CreateKlineSync(params currency.CreateKlineSyncParams) error {
	ret := _m.Called(params)

	var r0 error
	if rf, ok := ret.Get(0).(func(currency.CreateKlineSyncParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveTimeFrames provides a mock function with given fields:
func (_m *KlineService) GetActiveTimeFrames() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetAveragePriceOfPairsUsingTime provides a mock function with given fields: pairNames, startTime, endTime
func (_m *KlineService) GetAveragePriceOfPairsUsingTime(pairNames []string, startTime time.Time, endTime time.Time) ([]candle.AveragePairPrice, error) {
	ret := _m.Called(pairNames, startTime, endTime)

	var r0 []candle.AveragePairPrice
	if rf, ok := ret.Get(0).(func([]string, time.Time, time.Time) []candle.AveragePairPrice); ok {
		r0 = rf(pairNames, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]candle.AveragePairPrice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, time.Time, time.Time) error); ok {
		r1 = rf(pairNames, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHighAndLowPriceFromDateForPairByPairName provides a mock function with given fields: pairName, fromDate
func (_m *KlineService) GetHighAndLowPriceFromDateForPairByPairName(pairName string, fromDate time.Time) (candle.HighAndLowPrice, error) {
	ret := _m.Called(pairName, fromDate)

	var r0 candle.HighAndLowPrice
	if rf, ok := ret.Get(0).(func(string, time.Time) candle.HighAndLowPrice); ok {
		r0 = rf(pairName, fromDate)
	} else {
		r0 = ret.Get(0).(candle.HighAndLowPrice)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(pairName, fromDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKlineSyncsByStatusAndLimit provides a mock function with given fields: status, limit
func (_m *KlineService) GetKlineSyncsByStatusAndLimit(status string, limit int) []currency.KlineSync {
	ret := _m.Called(status, limit)

	var r0 []currency.KlineSync
	if rf, ok := ret.Get(0).(func(string, int) []currency.KlineSync); ok {
		r0 = rf(status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.KlineSync)
		}
	}

	return r0
}

// GetKlineTrends provides a mock function with given fields: pairNames, timeFrame, from, to
func (_m *KlineService) GetKlineTrends(pairNames []string, timeFrame string, from time.Time, to time.Time) ([]candle.CandleTrend, error) {
	ret := _m.Called(pairNames, timeFrame, from, to)

	var r0 []candle.CandleTrend
	if rf, ok := ret.Get(0).(func([]string, string, time.Time, time.Time) []candle.CandleTrend); ok {
		r0 = rf(pairNames, timeFrame, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]candle.CandleTrend)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, string, time.Time, time.Time) error); ok {
		r1 = rf(pairNames, timeFrame, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastPriceForPair provides a mock function with given fields: ctx, pairName, date
func (_m *KlineService) GetLastPriceForPair(ctx context.Context, pairName string, date time.Time) (string, error) {
	ret := _m.Called(ctx, pairName, date)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) string); ok {
		r0 = rf(ctx, pairName, date)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, pairName, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResolutionToTimeFrame provides a mock function with given fields: resolution
func (_m *KlineService) ResolutionToTimeFrame(resolution string) (string, error) {
	ret := _m.Called(resolution)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(resolution)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(resolution)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKlineSync provides a mock function with given fields: klineSync
func (_m *KlineService) UpdateKlineSync(klineSync *currency.KlineSync) error {
	ret := _m.Called(klineSync)

	var r0 error
	if rf, ok := ret.Get(0).(func(*currency.KlineSync) error); ok {
		r0 = rf(klineSync)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
