// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"
)

// KlineSyncRepository is an autogenerated mock type for the KlineSyncRepository type
type KlineSyncRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: klineSync
func (_m *KlineSyncRepository) Create(klineSync *currency.KlineSync) error {
	ret := _m.Called(klineSync)

	var r0 error
	if rf, ok := ret.Get(0).(func(*currency.KlineSync) error); ok {
		r0 = rf(klineSync)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetKlineSyncsByStatusAndLimit provides a mock function with given fields: status, limit
func (_m *KlineSyncRepository) GetKlineSyncsByStatusAndLimit(status string, limit int) []currency.KlineSync {
	ret := _m.Called(status, limit)

	var r0 []currency.KlineSync
	if rf, ok := ret.Get(0).(func(string, int) []currency.KlineSync); ok {
		r0 = rf(status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.KlineSync)
		}
	}

	return r0
}

// Update provides a mock function with given fields: klineSync
func (_m *KlineSyncRepository) Update(klineSync *currency.KlineSync) error {
	ret := _m.Called(klineSync)

	var r0 error
	if rf, ok := ret.Get(0).(func(*currency.KlineSync) error); ok {
		r0 = rf(klineSync)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
