// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	livedata "exchange-go/internal/livedata"

	mock "github.com/stretchr/testify/mock"
)

// LiveData is an autogenerated mock type for the Service type
type LiveData struct {
	mock.Mock
}

// GetDepthSnapshot provides a mock function with given fields: ctx, pairName
func (_m *LiveData) GetDepthSnapshot(ctx context.Context, pairName string) (livedata.RedisDepthSnapshot, error) {
	ret := _m.Called(ctx, pairName)

	var r0 livedata.RedisDepthSnapshot
	if rf, ok := ret.Get(0).(func(context.Context, string) livedata.RedisDepthSnapshot); ok {
		r0 = rf(ctx, pairName)
	} else {
		r0 = ret.Get(0).(livedata.RedisDepthSnapshot)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKline provides a mock function with given fields: ctx, pairName, timeFrame
func (_m *LiveData) GetKline(ctx context.Context, pairName string, timeFrame string) (livedata.RedisKline, error) {
	ret := _m.Called(ctx, pairName, timeFrame)

	var r0 livedata.RedisKline
	if rf, ok := ret.Get(0).(func(context.Context, string, string) livedata.RedisKline); ok {
		r0 = rf(ctx, pairName, timeFrame)
	} else {
		r0 = ret.Get(0).(livedata.RedisKline)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, pairName, timeFrame)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastAggregationTime provides a mock function with given fields: ctx, pairName
func (_m *LiveData) GetLastAggregationTime(ctx context.Context, pairName string) (string, error) {
	ret := _m.Called(ctx, pairName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, pairName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastInsertTime provides a mock function with given fields: ctx, pairName, fieldName
func (_m *LiveData) GetLastInsertTime(ctx context.Context, pairName string, fieldName string) (string, error) {
	ret := _m.Called(ctx, pairName, fieldName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, pairName, fieldName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, pairName, fieldName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderBook provides a mock function with given fields: ctx, pairName
func (_m *LiveData) GetOrderBook(ctx context.Context, pairName string) (livedata.RedisOrderBook, error) {
	ret := _m.Called(ctx, pairName)

	var r0 livedata.RedisOrderBook
	if rf, ok := ret.Get(0).(func(context.Context, string) livedata.RedisOrderBook); ok {
		r0 = rf(ctx, pairName)
	} else {
		r0 = ret.Get(0).(livedata.RedisOrderBook)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPairsPriceData provides a mock function with given fields: ctx, pairNames
func (_m *LiveData) GetPairsPriceData(ctx context.Context, pairNames []string) ([]livedata.RedisPairPriceData, error) {
	ret := _m.Called(ctx, pairNames)

	var r0 []livedata.RedisPairPriceData
	if rf, ok := ret.Get(0).(func(context.Context, []string) []livedata.RedisPairPriceData); ok {
		r0 = rf(ctx, pairNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]livedata.RedisPairPriceData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, pairNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreKline provides a mock function with given fields: ctx, pairName, timeFrame
func (_m *LiveData) GetPreKline(ctx context.Context, pairName string, timeFrame string) (livedata.RedisKline, error) {
	ret := _m.Called(ctx, pairName, timeFrame)

	var r0 livedata.RedisKline
	if rf, ok := ret.Get(0).(func(context.Context, string, string) livedata.RedisKline); ok {
		r0 = rf(ctx, pairName, timeFrame)
	} else {
		r0 = ret.Get(0).(livedata.RedisKline)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, pairName, timeFrame)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrice provides a mock function with given fields: ctx, pairName
func (_m *LiveData) GetPrice(ctx context.Context, pairName string) (string, error) {
	ret := _m.Called(ctx, pairName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, pairName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTradeBook provides a mock function with given fields: ctx, pairName
func (_m *LiveData) GetTradeBook(ctx context.Context, pairName string) ([]livedata.RedisTrade, error) {
	ret := _m.Called(ctx, pairName)

	var r0 []livedata.RedisTrade
	if rf, ok := ret.Get(0).(func(context.Context, string) []livedata.RedisTrade); ok {
		r0 = rf(ctx, pairName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]livedata.RedisTrade)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDepthSnapshot provides a mock function with given fields: ctx, pairName, snapshot
func (_m *LiveData) SetDepthSnapshot(ctx context.Context, pairName string, snapshot livedata.RedisDepthSnapshot) error {
	ret := _m.Called(ctx, pairName, snapshot)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, livedata.RedisDepthSnapshot) error); ok {
		r0 = rf(ctx, pairName, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetKline provides a mock function with given fields: ctx, pairName, kline
func (_m *LiveData) SetKline(ctx context.Context, pairName string, kline livedata.RedisKline) error {
	ret := _m.Called(ctx, pairName, kline)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, livedata.RedisKline) error); ok {
		r0 = rf(ctx, pairName, kline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLastAggregationTime provides a mock function with given fields: ctx, pairName, timestamp
func (_m *LiveData) SetLastAggregationTime(ctx context.Context, pairName string, timestamp int64) error {
	ret := _m.Called(ctx, pairName, timestamp)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, pairName, timestamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOrderBook provides a mock function with given fields: ctx, pairName, orderBook
func (_m *LiveData) SetOrderBook(ctx context.Context, pairName string, orderBook livedata.RedisOrderBook) error {
	ret := _m.Called(ctx, pairName, orderBook)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, livedata.RedisOrderBook) error); ok {
		r0 = rf(ctx, pairName, orderBook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPriceData provides a mock function with given fields: ctx, pairName, price, percentage, volume
func (_m *LiveData) SetPriceData(ctx context.Context, pairName string, price string, percentage string, volume string) error {
	ret := _m.Called(ctx, pairName, price, percentage, volume)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, pairName, price, percentage, volume)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTradeBook provides a mock function with given fields: ctx, pairName, trade
func (_m *LiveData) UpdateTradeBook(ctx context.Context, pairName string, trade livedata.RedisTrade) error {
	ret := _m.Called(ctx, pairName, trade)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, livedata.RedisTrade) error); ok {
		r0 = rf(ctx, pairName, trade)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
