// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// LoginHistoryService is an autogenerated mock type for the LoginHistoryService type
type LoginHistoryService struct {
	mock.Mock
}

// CreateLoginHistory provides a mock function with given fields: loginHistory
func (_m *LoginHistoryService) CreateLoginHistory(loginHistory *user.LoginHistory) error {
	ret := _m.Called(loginHistory)

	var r0 error
	if rf, ok := ret.Get(0).(func(*user.LoginHistory) error); ok {
		r0 = rf(loginHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastLoginHistoryByUserID provides a mock function with given fields: userID, loginHistory
func (_m *LoginHistoryService) GetLastLoginHistoryByUserID(userID int, loginHistory *user.LoginHistory) error {
	ret := _m.Called(userID, loginHistory)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *user.LoginHistory) error); ok {
		r0 = rf(userID, loginHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
