// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MqttManager is an autogenerated mock type for the MqttManager type
type MqttManager struct {
	mock.Mock
}

// PublishKline provides a mock function with given fields: ctx, pairName, timeFrame, payload
func (_m *MqttManager) PublishKline(ctx context.Context, pairName string, timeFrame string, payload []byte) {
	_m.Called(ctx, pairName, timeFrame, payload)
}

// PublishOrderBook provides a mock function with given fields: ctx, pairName, payload
func (_m *MqttManager) PublishOrderBook(ctx context.Context, pairName string, payload []byte) {
	_m.Called(ctx, pairName, payload)
}

// PublishOrderToOpenOrders provides a mock function with given fields: ctx, privateChannelName, payload
func (_m *MqttManager) PublishOrderToOpenOrders(ctx context.Context, privateChannelName string, payload []byte) {
	_m.Called(ctx, privateChannelName, payload)
}

// PublishPayment provides a mock function with given fields: ctx, privateChannelName, payload
func (_m *MqttManager) PublishPayment(ctx context.Context, privateChannelName string, payload []byte) {
	_m.Called(ctx, privateChannelName, payload)
}

// PublishTicker provides a mock function with given fields: ctx, pairName, payload
func (_m *MqttManager) PublishTicker(ctx context.Context, pairName string, payload []byte) {
	_m.Called(ctx, pairName, payload)
}

// PublishTrades provides a mock function with given fields: ctx, pairName, payload
func (_m *MqttManager) PublishTrades(ctx context.Context, pairName string, payload []byte) {
	_m.Called(ctx, pairName, payload)
}
