// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
)

// OrderCreateManager is an autogenerated mock type for the CreateManager type
type OrderCreateManager struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: data
func (_m *OrderCreateManager) CreateOrder(data order.CreateRequiredData) (*order.Order, error) {
	ret := _m.Called(data)

	var r0 *order.Order
	if rf, ok := ret.Get(0).(func(order.CreateRequiredData) *order.Order); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(order.CreateRequiredData) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
