// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	orderbook "exchange-go/internal/orderbook"

	mock "github.com/stretchr/testify/mock"

	response "exchange-go/internal/response"
)

// OrderbookService is an autogenerated mock type for the Service type
type OrderbookService struct {
	mock.Mock
}

// GetOrderBook provides a mock function with given fields: params
func (_m *OrderbookService) GetOrderBook(params orderbook.GetOrderBookParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(orderbook.GetOrderBookParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(orderbook.GetOrderBookParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetTradeBook provides a mock function with given fields: params
func (_m *OrderbookService) GetTradeBook(params orderbook.GetTradeBookParams) (response.APIResponse, int) {
	ret := _m.Called(params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(orderbook.GetTradeBookParams) response.APIResponse); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(orderbook.GetTradeBookParams) int); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// UpdateExternalOrderBook provides a mock function with given fields: ctx, externalExchangeName, pairName, externalExchangePairName, precision, data
func (_m *OrderbookService) UpdateExternalOrderBook(ctx context.Context, externalExchangeName string, pairName string, externalExchangePairName string, precision int, data []byte) (orderbook.OrderBook, error) {
	ret := _m.Called(ctx, externalExchangeName, pairName, externalExchangePairName, precision, data)

	var r0 orderbook.OrderBook
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, []byte) orderbook.OrderBook); ok {
		r0 = rf(ctx, externalExchangeName, pairName, externalExchangePairName, precision, data)
	} else {
		r0 = ret.Get(0).(orderbook.OrderBook)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, []byte) error); ok {
		r1 = rf(ctx, externalExchangeName, pairName, externalExchangePairName, precision, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
