// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// OrderRepository is an autogenerated mock type for the Repository type
type OrderRepository struct {
	mock.Mock
}

// GetLeafOrders provides a mock function with given fields: filters
func (_m *OrderRepository) GetLeafOrders(filters order.HistoryFilters) []order.HistoryNeededField {
	ret := _m.Called(filters)

	var r0 []order.HistoryNeededField
	if rf, ok := ret.Get(0).(func(order.HistoryFilters) []order.HistoryNeededField); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.HistoryNeededField)
		}
	}

	return r0
}

// GetOpenOrders provides a mock function with given fields: date
func (_m *OrderRepository) GetOpenOrders(date string) []order.Order {
	ret := _m.Called(date)

	var r0 []order.Order
	if rf, ok := ret.Get(0).(func(string) []order.Order); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}

	return r0
}

// GetOrderByID provides a mock function with given fields: id, o
func (_m *OrderRepository) GetOrderByID(id int64, o *order.Order) error {
	ret := _m.Called(id, o)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *order.Order) error); ok {
		r0 = rf(id, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderByIDUsingTx provides a mock function with given fields: tx, id, o
func (_m *OrderRepository) GetOrderByIDUsingTx(tx *gorm.DB, id int64, o *order.Order) error {
	ret := _m.Called(tx, id, o)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int64, *order.Order) error); ok {
		r0 = rf(tx, id, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrdersAncestors provides a mock function with given fields: ancestorsIds
func (_m *OrderRepository) GetOrdersAncestors(ancestorsIds []int64) []order.Order {
	ret := _m.Called(ancestorsIds)

	var r0 []order.Order
	if rf, ok := ret.Get(0).(func([]int64) []order.Order); ok {
		r0 = rf(ancestorsIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}

	return r0
}

// GetOrdersByIds provides a mock function with given fields: orderIds
func (_m *OrderRepository) GetOrdersByIds(orderIds []int64) []order.Order {
	ret := _m.Called(orderIds)

	var r0 []order.Order
	if rf, ok := ret.Get(0).(func([]int64) []order.Order); ok {
		r0 = rf(orderIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}

	return r0
}

// GetOrdersDataByIdsWithJoinUsingTx provides a mock function with given fields: tx, orderIds
func (_m *OrderRepository) GetOrdersDataByIdsWithJoinUsingTx(tx *gorm.DB, orderIds []int64) []order.MatchingNeededQueryFields {
	ret := _m.Called(tx, orderIds)

	var r0 []order.MatchingNeededQueryFields
	if rf, ok := ret.Get(0).(func(*gorm.DB, []int64) []order.MatchingNeededQueryFields); ok {
		r0 = rf(tx, orderIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.MatchingNeededQueryFields)
		}
	}

	return r0
}

// GetUserOpenOrders provides a mock function with given fields: userID, pairID
func (_m *OrderRepository) GetUserOpenOrders(userID int, pairID int64) []order.Order {
	ret := _m.Called(userID, pairID)

	var r0 []order.Order
	if rf, ok := ret.Get(0).(func(int, int64) []order.Order); ok {
		r0 = rf(userID, pairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}

	return r0
}

// GetUserOrderDetailsByID provides a mock function with given fields: id, userID
func (_m *OrderRepository) GetUserOrderDetailsByID(id int64, userID int) []order.Order {
	ret := _m.Called(id, userID)

	var r0 []order.Order
	if rf, ok := ret.Get(0).(func(int64, int) []order.Order); ok {
		r0 = rf(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}

	return r0
}

// GetUserTradedOrders provides a mock function with given fields: filters
func (_m *OrderRepository) GetUserTradedOrders(filters order.TradeHistoryFilters) []order.Order {
	ret := _m.Called(filters)

	var r0 []order.Order
	if rf, ok := ret.Get(0).(func(order.TradeHistoryFilters) []order.Order); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}

	return r0
}
