// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
)

// EventsHandler is an autogenerated mock type for the EventsHandler type
type EventsHandler struct {
	mock.Mock
}

// HandleOrderCancellation provides a mock function with given fields: o
func (_m *EventsHandler) HandleOrderCancellation(o order.Order) {
	_m.Called(o)
}

// HandleOrderCreation provides a mock function with given fields: o, isForStopOrderSubmission
func (_m *EventsHandler) HandleOrderCreation(o order.Order, isForStopOrderSubmission bool) {
	_m.Called(o, isForStopOrderSubmission)
}

// HandleOrderFulfillByAdmin provides a mock function with given fields: o
func (_m *EventsHandler) HandleOrderFulfillByAdmin(o order.Order) {
	_m.Called(o)
}
