// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	externalexchange "exchange-go/internal/externalexchange"

	mock "github.com/stretchr/testify/mock"
)

// OrderFromExternalRepository is an autogenerated mock type for the OrderFromExternalRepository type
type OrderFromExternalRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: orderFromExternal
func (_m *OrderFromExternalRepository) Create(orderFromExternal *externalexchange.OrderFromExternal) error {
	ret := _m.Called(orderFromExternal)

	var r0 error
	if rf, ok := ret.Get(0).(func(*externalexchange.OrderFromExternal) error); ok {
		r0 = rf(orderFromExternal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastOrderFromExternalByPairID provides a mock function with given fields: pairID, orderFromExternal
func (_m *OrderFromExternalRepository) GetLastOrderFromExternalByPairID(pairID int64, orderFromExternal *externalexchange.OrderFromExternal) error {
	ret := _m.Called(pairID, orderFromExternal)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *externalexchange.OrderFromExternal) error); ok {
		r0 = rf(pairID, orderFromExternal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderByExternalOrderID provides a mock function with given fields: externalOrderID, orderFromExternal
func (_m *OrderFromExternalRepository) GetOrderByExternalOrderID(externalOrderID int64, orderFromExternal *externalexchange.OrderFromExternal) error {
	ret := _m.Called(externalOrderID, orderFromExternal)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *externalexchange.OrderFromExternal) error); ok {
		r0 = rf(externalOrderID, orderFromExternal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
