// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"

	redis "github.com/go-redis/redis/v8"
)

// OrderRedisManager is an autogenerated mock type for the RedisManager type
type OrderRedisManager struct {
	mock.Mock
}

// AddStopOrderToQueue provides a mock function with given fields: ctx, o
func (_m *OrderRedisManager) AddStopOrderToQueue(ctx context.Context, o order.Order) error {
	ret := _m.Called(ctx, o)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, order.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, o
func (_m *OrderRedisManager) Exists(ctx context.Context, o order.Order) (bool, error) {
	ret := _m.Called(ctx, o)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, order.Order) bool); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, order.Order) error); ok {
		r1 = rf(ctx, o)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStopOrdersFromQueue provides a mock function with given fields: ctx, pairName, formerPrice, price, isPriceRising
func (_m *OrderRedisManager) GetStopOrdersFromQueue(ctx context.Context, pairName string, formerPrice string, price string, isPriceRising bool) ([]redis.Z, error) {
	ret := _m.Called(ctx, pairName, formerPrice, price, isPriceRising)

	var r0 []redis.Z
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) []redis.Z); ok {
		r0 = rf(ctx, pairName, formerPrice, price, isPriceRising)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]redis.Z)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = rf(ctx, pairName, formerPrice, price, isPriceRising)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveStopOrderFromQueue provides a mock function with given fields: ctx, o, pairName
func (_m *OrderRedisManager) RemoveStopOrderFromQueue(ctx context.Context, o order.Order, pairName string) error {
	ret := _m.Called(ctx, o, pairName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, order.Order, string) error); ok {
		r0 = rf(ctx, o, pairName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
