// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"
)

// PairRepository is an autogenerated mock type for the PairRepository type
type PairRepository struct {
	mock.Mock
}

// GetActivePairCurrenciesList provides a mock function with given fields:
func (_m *PairRepository) GetActivePairCurrenciesList() []currency.Pair {
	ret := _m.Called()

	var r0 []currency.Pair
	if rf, ok := ret.Get(0).(func() []currency.Pair); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.Pair)
		}
	}

	return r0
}

// GetAllPairs provides a mock function with given fields:
func (_m *PairRepository) GetAllPairs() []currency.Pair {
	ret := _m.Called()

	var r0 []currency.Pair
	if rf, ok := ret.Get(0).(func() []currency.Pair); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.Pair)
		}
	}

	return r0
}

// GetPairByID provides a mock function with given fields: id, pair
func (_m *PairRepository) GetPairByID(id int64, pair *currency.Pair) error {
	ret := _m.Called(id, pair)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *currency.Pair) error); ok {
		r0 = rf(id, pair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPairByName provides a mock function with given fields: name, pair
func (_m *PairRepository) GetPairByName(name string, pair *currency.Pair) error {
	ret := _m.Called(name, pair)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *currency.Pair) error); ok {
		r0 = rf(name, pair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPairsByName provides a mock function with given fields: names
func (_m *PairRepository) GetPairsByName(names []string) []currency.Pair {
	ret := _m.Called(names)

	var r0 []currency.Pair
	if rf, ok := ret.Get(0).(func([]string) []currency.Pair); ok {
		r0 = rf(names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]currency.Pair)
		}
	}

	return r0
}
