// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payment "exchange-go/internal/payment"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// PaymentRepository is an autogenerated mock type for the Repository type
type PaymentRepository struct {
	mock.Mock
}

// GetExtraInfoByPaymentID provides a mock function with given fields: paymentID, extraInfo
func (_m *PaymentRepository) GetExtraInfoByPaymentID(paymentID int64, extraInfo *payment.ExtraInfo) error {
	ret := _m.Called(paymentID, extraInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *payment.ExtraInfo) error); ok {
		r0 = rf(paymentID, extraInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExtraInfoByPaymentIDUsingTx provides a mock function with given fields: tx, paymentID, extraInfo
func (_m *PaymentRepository) GetExtraInfoByPaymentIDUsingTx(tx *gorm.DB, paymentID int64, extraInfo *payment.ExtraInfo) error {
	ret := _m.Called(tx, paymentID, extraInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int64, *payment.ExtraInfo) error); ok {
		r0 = rf(tx, paymentID, extraInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInProgressWithdrawalsInExternalExchange provides a mock function with given fields:
func (_m *PaymentRepository) GetInProgressWithdrawalsInExternalExchange() []payment.ExternalWithdrawalUpdateDataNeeded {
	ret := _m.Called()

	var r0 []payment.ExternalWithdrawalUpdateDataNeeded
	if rf, ok := ret.Get(0).(func() []payment.ExternalWithdrawalUpdateDataNeeded); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.ExternalWithdrawalUpdateDataNeeded)
		}
	}

	return r0
}

// GetPaymentByCoinIDAndTxIDAndTypeUsingTx provides a mock function with given fields: tx, coinID, txID, txType, _a4
func (_m *PaymentRepository) GetPaymentByCoinIDAndTxIDAndTypeUsingTx(tx *gorm.DB, coinID int64, txID string, txType string, _a4 *payment.Payment) error {
	ret := _m.Called(tx, coinID, txID, txType, _a4)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int64, string, string, *payment.Payment) error); ok {
		r0 = rf(tx, coinID, txID, txType, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentByID provides a mock function with given fields: id, _a1
func (_m *PaymentRepository) GetPaymentByID(id int64, _a1 *payment.Payment) error {
	ret := _m.Called(id, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *payment.Payment) error); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentByIDUsingTx provides a mock function with given fields: tx, id, _a2
func (_m *PaymentRepository) GetPaymentByIDUsingTx(tx *gorm.DB, id int64, _a2 *payment.Payment) error {
	ret := _m.Called(tx, id, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int64, *payment.Payment) error); ok {
		r0 = rf(tx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentDetailByID provides a mock function with given fields: paymentID
func (_m *PaymentRepository) GetPaymentDetailByID(paymentID int64) (payment.DetailQueryFields, error) {
	ret := _m.Called(paymentID)

	var r0 payment.DetailQueryFields
	if rf, ok := ret.Get(0).(func(int64) payment.DetailQueryFields); ok {
		r0 = rf(paymentID)
	} else {
		r0 = ret.Get(0).(payment.DetailQueryFields)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPayments provides a mock function with given fields: filters
func (_m *PaymentRepository) GetUserPayments(filters payment.GetPaymentFilters) []payment.Payment {
	ret := _m.Called(filters)

	var r0 []payment.Payment
	if rf, ok := ret.Get(0).(func(payment.GetPaymentFilters) []payment.Payment); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Payment)
		}
	}

	return r0
}
