// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	"exchange-go/internal/user"

	"github.com/stretchr/testify/mock"
)

// PhoneConfirmationManager is an autogenerated mock type for the PhoneConfirmationManager type
type PhoneConfirmationManager struct {
	mock.Mock
}

// DeleteKey provides a mock function with given fields: u
func (_m *PhoneConfirmationManager) DeleteKey(u user.User) error {
	ret := _m.Called(u)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GeneratePhoneConfirmationCodeAndSendSms provides a mock function with given fields: u, phone
func (_m *PhoneConfirmationManager) GeneratePhoneConfirmationCodeAndSendSms(u user.User, phone string) error {
	ret := _m.Called(u, phone)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.User, string) error); ok {
		r0 = rf(u, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsAllowedToSendSms provides a mock function with given fields: u
func (_m *PhoneConfirmationManager) IsAllowedToSendSms(u user.User) bool {
	ret := _m.Called(u)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.User) bool); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsCodeCorrect provides a mock function with given fields: u, phone, code
func (_m *PhoneConfirmationManager) IsCodeCorrect(u user.User, phone string, code string) bool {
	ret := _m.Called(u, phone, code)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.User, string, string) bool); ok {
		r0 = rf(u, phone, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
