// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
)

// PostOrderMatchingService is an autogenerated mock type for the PostOrderMatchingService type
type PostOrderMatchingService struct {
	mock.Mock
}

// HandleExternalTradedOrder provides a mock function with given fields: data
func (_m *PostOrderMatchingService) HandleExternalTradedOrder(data order.ExternalTradedOrderData) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(order.ExternalTradedOrderData) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlePostOrderMatching provides a mock function with given fields: ordersData, partial, isFromAdmin
func (_m *PostOrderMatchingService) HandlePostOrderMatching(ordersData []order.CallBackOrderData, partial *order.CallBackOrderData, isFromAdmin bool) order.MatchingResult {
	ret := _m.Called(ordersData, partial, isFromAdmin)

	var r0 order.MatchingResult
	if rf, ok := ret.Get(0).(func([]order.CallBackOrderData, *order.CallBackOrderData, bool) order.MatchingResult); ok {
		r0 = rf(ordersData, partial, isFromAdmin)
	} else {
		r0 = ret.Get(0).(order.MatchingResult)
	}

	return r0
}
