// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PriceGenerator is an autogenerated mock type for the PriceGenerator type
type PriceGenerator struct {
	mock.Mock
}

// GetAmountBasedOnBTC provides a mock function with given fields: ctx, coin, amount
func (_m *PriceGenerator) GetAmountBasedOnBTC(ctx context.Context, coin string, amount string) (string, error) {
	ret := _m.Called(ctx, coin, amount)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, coin, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, coin, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAmountBasedOnUSDT provides a mock function with given fields: ctx, coin, amount
func (_m *PriceGenerator) GetAmountBasedOnUSDT(ctx context.Context, coin string, amount string) (string, error) {
	ret := _m.Called(ctx, coin, amount)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, coin, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, coin, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBTCUSDTPrice provides a mock function with given fields: ctx
func (_m *PriceGenerator) GetBTCUSDTPrice(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPairPriceBasedOnUSDT provides a mock function with given fields: ctx, pairName
func (_m *PriceGenerator) GetPairPriceBasedOnUSDT(ctx context.Context, pairName string) (string, error) {
	ret := _m.Called(ctx, pairName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, pairName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrice provides a mock function with given fields: ctx, pairName
func (_m *PriceGenerator) GetPrice(ctx context.Context, pairName string) (string, error) {
	ret := _m.Called(ctx, pairName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, pairName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pairName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
