// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	"context"
	"exchange-go/internal/processor"

	"github.com/stretchr/testify/mock"
)

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

// ProcessDepth provides a mock function with given fields: ctx, externalExchangeName, pairName, externalExchangePairName, data
func (_m *Processor) ProcessDepth(ctx context.Context, externalExchangeName string, pairName string, externalExchangePairName string, data []byte) {
	_m.Called(ctx, externalExchangeName, pairName, externalExchangePairName, data)
}

// ProcessKline provides a mock function with given fields: ctx, kline
func (_m *Processor) ProcessKline(ctx context.Context, kline processor.Kline) {
	_m.Called(ctx, kline)
}

// ProcessTicker provides a mock function with given fields: ctx, ticker
func (_m *Processor) ProcessTicker(ctx context.Context, ticker processor.Ticker) {
	_m.Called(ctx, ticker)
}

// ProcessTrade provides a mock function with given fields: ctx, trade
func (_m *Processor) ProcessTrade(ctx context.Context, trade processor.Trade) {
	_m.Called(ctx, trade)
}
