// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// ProfileImageRepository is an autogenerated mock type for the ProfileImageRepository type
type ProfileImageRepository struct {
	mock.Mock
}

// GetImageByID provides a mock function with given fields: id, upi
func (_m *ProfileImageRepository) GetImageByID(id int64, upi *user.ProfileImage) error {
	ret := _m.Called(id, upi)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *user.ProfileImage) error); ok {
		r0 = rf(id, upi)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetImagesByIds provides a mock function with given fields: ids
func (_m *ProfileImageRepository) GetImagesByIds(ids []int64) []user.ProfileImage {
	ret := _m.Called(ids)

	var r0 []user.ProfileImage
	if rf, ok := ret.Get(0).(func([]int64) []user.ProfileImage); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.ProfileImage)
		}
	}

	return r0
}

// GetLatestImagesDataByProfileID provides a mock function with given fields: profileID
func (_m *ProfileImageRepository) GetLatestImagesDataByProfileID(profileID int64) []user.ImagesQueryFields {
	ret := _m.Called(profileID)

	var r0 []user.ImagesQueryFields
	if rf, ok := ret.Get(0).(func(int64) []user.ImagesQueryFields); ok {
		r0 = rf(profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.ImagesQueryFields)
		}
	}

	return r0
}
