// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QueueManager is an autogenerated mock type for the QueueManager type
type QueueManager struct {
	mock.Mock
}

// PublishEmailOrSms provides a mock function with given fields: data
func (_m *QueueManager) PublishEmailOrSms(data []byte) {
	_m.Called(data)
}

// PublishKline provides a mock function with given fields: data
func (_m *QueueManager) PublishKline(data []byte) {
	_m.Called(data)
}
