// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RecaptchaManager is an autogenerated mock type for the RecaptchaManager type
type RecaptchaManager struct {
	mock.Mock
}

// CheckRecaptcha provides a mock function with given fields: captchaResponse, device, ip
func (_m *RecaptchaManager) CheckRecaptcha(captchaResponse string, device string, ip string) (bool, error) {
	ret := _m.Called(captchaResponse, device, ip)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(captchaResponse, device, ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(captchaResponse, device, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
