// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	order "exchange-go/internal/order"

	mock "github.com/stretchr/testify/mock"
)

// StopOrderSubmissionManager is an autogenerated mock type for the StopOrderSubmissionManager type
type StopOrderSubmissionManager struct {
	mock.Mock
}

// Submit provides a mock function with given fields: ctx, pairName, price, formerPrice
func (_m *StopOrderSubmissionManager) Submit(ctx context.Context, pairName string, price string, formerPrice string) {
	_m.Called(ctx, pairName, price, formerPrice)
}

// SubmitOrderInDb provides a mock function with given fields: ctx, _a1, price
func (_m *StopOrderSubmissionManager) SubmitOrderInDb(ctx context.Context, _a1 *order.Order, price string) error {
	ret := _m.Called(ctx, _a1, price)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *order.Order, string) error); ok {
		r0 = rf(ctx, _a1, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
