// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"

	order "exchange-go/internal/order"
)

// TradeEventsHandler is an autogenerated mock type for the TradeEventsHandler type
type TradeEventsHandler struct {
	mock.Mock
}

// HandleTradesCreation provides a mock function with given fields: tradesDate, pair
func (_m *TradeEventsHandler) HandleTradesCreation(tradesDate []order.TradeData, pair currency.Pair) {
	_m.Called(tradesDate, pair)
}
