// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	externalexchange "exchange-go/internal/externalexchange"

	mock "github.com/stretchr/testify/mock"
)

// TradeFromExternalRepository is an autogenerated mock type for the TradeFromExternalRepository type
type TradeFromExternalRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: tradeFromExternal
func (_m *TradeFromExternalRepository) Create(tradeFromExternal *externalexchange.TradeFromExternal) error {
	ret := _m.Called(tradeFromExternal)

	var r0 error
	if rf, ok := ret.Get(0).(func(*externalexchange.TradeFromExternal) error); ok {
		r0 = rf(tradeFromExternal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastTradeFromExternalByPairID provides a mock function with given fields: pairID, tradeFromExternal
func (_m *TradeFromExternalRepository) GetLastTradeFromExternalByPairID(pairID int64, tradeFromExternal *externalexchange.TradeFromExternal) error {
	ret := _m.Called(pairID, tradeFromExternal)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *externalexchange.TradeFromExternal) error); ok {
		r0 = rf(pairID, tradeFromExternal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
