// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// TwoFaManager is an autogenerated mock type for the TwoFaManager type
type TwoFaManager struct {
	mock.Mock
}

// CheckCode provides a mock function with given fields: u, code
func (_m *TwoFaManager) CheckCode(u user.User, code string) bool {
	ret := _m.Called(u, code)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.User, string) bool); ok {
		r0 = rf(u, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GenerateSecretCode provides a mock function with given fields: u
func (_m *TwoFaManager) GenerateSecretCode(u user.User) (string, string, error) {
	ret := _m.Called(u)

	var r0 string
	if rf, ok := ret.Get(0).(func(user.User) string); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(user.User) string); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(user.User) error); ok {
		r2 = rf(u)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
