// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnmatchedOrdersHandler is an autogenerated mock type for the UnmatchedOrdersHandler type
type UnmatchedOrdersHandler struct {
	mock.Mock
}

// AddUnmatchedOrderIdToList provides a mock function with given fields: orderId
func (_m *UnmatchedOrdersHandler) AddUnmatchedOrderIdToList(orderId int64) {
	_m.Called(orderId)
}
