// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserLevelService is an autogenerated mock type for the LevelService type
type UserLevelService struct {
	mock.Mock
}

// GetLevelByCode provides a mock function with given fields: code
func (_m *UserLevelService) GetLevelByCode(code int64) (user.Level, error) {
	ret := _m.Called(code)

	var r0 user.Level
	if rf, ok := ret.Get(0).(func(int64) user.Level); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(user.Level)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLevelByID provides a mock function with given fields: id
func (_m *UserLevelService) GetLevelByID(id int64) (user.Level, error) {
	ret := _m.Called(id)

	var r0 user.Level
	if rf, ok := ret.Get(0).(func(int64) user.Level); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.Level)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLevelsByIds provides a mock function with given fields: ids
func (_m *UserLevelService) GetLevelsByIds(ids []int64) []user.Level {
	ret := _m.Called(ids)

	var r0 []user.Level
	if rf, ok := ret.Get(0).(func([]int64) []user.Level); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Level)
		}
	}

	return r0
}

// RecalculateUserLevel provides a mock function with given fields: u, exchangeVolume
func (_m *UserLevelService) RecalculateUserLevel(u user.User, exchangeVolume string) user.Level {
	ret := _m.Called(u, exchangeVolume)

	var r0 user.Level
	if rf, ok := ret.Get(0).(func(user.User, string) user.Level); ok {
		r0 = rf(u, exchangeVolume)
	} else {
		r0 = ret.Get(0).(user.Level)
	}

	return r0
}
