// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	userwithdrawaddress "exchange-go/internal/userwithdrawaddress"

	mock "github.com/stretchr/testify/mock"
)

// UserWithdrawAddressRepository is an autogenerated mock type for the Repository type
type UserWithdrawAddressRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: uwa
func (_m *UserWithdrawAddressRepository) Create(uwa *userwithdrawaddress.UserWithdrawAddress) error {
	ret := _m.Called(uwa)

	var r0 error
	if rf, ok := ret.Get(0).(func(*userwithdrawaddress.UserWithdrawAddress) error); ok {
		r0 = rf(uwa)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserWithdrawAddressByID provides a mock function with given fields: id, uwa
func (_m *UserWithdrawAddressRepository) GetUserWithdrawAddressByID(id int64, uwa *userwithdrawaddress.UserWithdrawAddress) error {
	ret := _m.Called(id, uwa)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *userwithdrawaddress.UserWithdrawAddress) error); ok {
		r0 = rf(id, uwa)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserWithdrawAddresses provides a mock function with given fields: filters
func (_m *UserWithdrawAddressRepository) GetUserWithdrawAddresses(filters userwithdrawaddress.GetWithdrawAddressesFilters) []userwithdrawaddress.UserWithdrawAddress {
	ret := _m.Called(filters)

	var r0 []userwithdrawaddress.UserWithdrawAddress
	if rf, ok := ret.Get(0).(func(userwithdrawaddress.GetWithdrawAddressesFilters) []userwithdrawaddress.UserWithdrawAddress); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userwithdrawaddress.UserWithdrawAddress)
		}
	}

	return r0
}

// GetUserWithdrawAddressesByAddress provides a mock function with given fields: userID, coinID, address
func (_m *UserWithdrawAddressRepository) GetUserWithdrawAddressesByAddress(userID int, coinID int64, address string) []userwithdrawaddress.UserWithdrawAddress {
	ret := _m.Called(userID, coinID, address)

	var r0 []userwithdrawaddress.UserWithdrawAddress
	if rf, ok := ret.Get(0).(func(int, int64, string) []userwithdrawaddress.UserWithdrawAddress); ok {
		r0 = rf(userID, coinID, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userwithdrawaddress.UserWithdrawAddress)
		}
	}

	return r0
}

// GetUserWithdrawAddressesByCoinID provides a mock function with given fields: userID, coinID
func (_m *UserWithdrawAddressRepository) GetUserWithdrawAddressesByCoinID(userID int, coinID int64) []userwithdrawaddress.UserWithdrawAddress {
	ret := _m.Called(userID, coinID)

	var r0 []userwithdrawaddress.UserWithdrawAddress
	if rf, ok := ret.Get(0).(func(int, int64) []userwithdrawaddress.UserWithdrawAddress); ok {
		r0 = rf(userID, coinID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userwithdrawaddress.UserWithdrawAddress)
		}
	}

	return r0
}

// GetUserWithdrawAddressesByIds provides a mock function with given fields: userID, ids
func (_m *UserWithdrawAddressRepository) GetUserWithdrawAddressesByIds(userID int, ids []int64) []userwithdrawaddress.UserWithdrawAddress {
	ret := _m.Called(userID, ids)

	var r0 []userwithdrawaddress.UserWithdrawAddress
	if rf, ok := ret.Get(0).(func(int, []int64) []userwithdrawaddress.UserWithdrawAddress); ok {
		r0 = rf(userID, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userwithdrawaddress.UserWithdrawAddress)
		}
	}

	return r0
}
