// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	userbalance "exchange-go/internal/userbalance"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// UserBalanceRepository is an autogenerated mock type for the Repository type
type UserBalanceRepository struct {
	mock.Mock
}

// GetBalanceOfUserByCoinID provides a mock function with given fields: userID, coinID, balance
func (_m *UserBalanceRepository) GetBalanceOfUserByCoinID(userID int, coinID int64, balance *userbalance.UserBalance) error {
	ret := _m.Called(userID, coinID, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int64, *userbalance.UserBalance) error); ok {
		r0 = rf(userID, coinID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalanceOfUserByCoinIDUsingTx provides a mock function with given fields: tx, userID, coinID, balance
func (_m *UserBalanceRepository) GetBalanceOfUserByCoinIDUsingTx(tx *gorm.DB, userID int, coinID int64, balance *userbalance.UserBalance) error {
	ret := _m.Called(tx, userID, coinID, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, int64, *userbalance.UserBalance) error); ok {
		r0 = rf(tx, userID, coinID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalancesOfUsersForCoins provides a mock function with given fields: userIds, coinIds
func (_m *UserBalanceRepository) GetBalancesOfUsersForCoins(userIds []int, coinIds []int64) []userbalance.UserBalance {
	ret := _m.Called(userIds, coinIds)

	var r0 []userbalance.UserBalance
	if rf, ok := ret.Get(0).(func([]int, []int64) []userbalance.UserBalance); ok {
		r0 = rf(userIds, coinIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userbalance.UserBalance)
		}
	}

	return r0
}

// GetBalancesOfUsersForCoinsUsingTx provides a mock function with given fields: tx, userIds, coinIds
func (_m *UserBalanceRepository) GetBalancesOfUsersForCoinsUsingTx(tx *gorm.DB, userIds []int, coinIds []int64) []userbalance.UserBalance {
	ret := _m.Called(tx, userIds, coinIds)

	var r0 []userbalance.UserBalance
	if rf, ok := ret.Get(0).(func(*gorm.DB, []int, []int64) []userbalance.UserBalance); ok {
		r0 = rf(tx, userIds, coinIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userbalance.UserBalance)
		}
	}

	return r0
}

// GetBalancesWithoutAddresses provides a mock function with given fields: filters
func (_m *UserBalanceRepository) GetBalancesWithoutAddresses(filters map[string]interface{}) []userbalance.UserBalance {
	ret := _m.Called(filters)

	var r0 []userbalance.UserBalance
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []userbalance.UserBalance); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userbalance.UserBalance)
		}
	}

	return r0
}

// GetUserAllBalances provides a mock function with given fields: userID, filters
func (_m *UserBalanceRepository) GetUserAllBalances(userID int, filters userbalance.AllBalancesFilters) []userbalance.UserBalance {
	ret := _m.Called(userID, filters)

	var r0 []userbalance.UserBalance
	if rf, ok := ret.Get(0).(func(int, userbalance.AllBalancesFilters) []userbalance.UserBalance); ok {
		r0 = rf(userID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userbalance.UserBalance)
		}
	}

	return r0
}

// GetUserBalanceByCoinAndAddressUsingTx provides a mock function with given fields: tx, coinID, address, ub
func (_m *UserBalanceRepository) GetUserBalanceByCoinAndAddressUsingTx(tx *gorm.DB, coinID int64, address string, ub *userbalance.UserBalance) error {
	ret := _m.Called(tx, coinID, address, ub)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int64, string, *userbalance.UserBalance) error); ok {
		r0 = rf(tx, coinID, address, ub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserBalanceByIDUsingTx provides a mock function with given fields: tx, id, ub
func (_m *UserBalanceRepository) GetUserBalanceByIDUsingTx(tx *gorm.DB, id int64, ub *userbalance.UserBalance) error {
	ret := _m.Called(tx, id, ub)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int64, *userbalance.UserBalance) error); ok {
		r0 = rf(tx, id, ub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserBalancesForCoins provides a mock function with given fields: userID, coinIds
func (_m *UserBalanceRepository) GetUserBalancesForCoins(userID int, coinIds []int64) []userbalance.UserBalance {
	ret := _m.Called(userID, coinIds)

	var r0 []userbalance.UserBalance
	if rf, ok := ret.Get(0).(func(int, []int64) []userbalance.UserBalance); ok {
		r0 = rf(userID, coinIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userbalance.UserBalance)
		}
	}

	return r0
}
