// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// UserRepository is an autogenerated mock type for the Repository type
type UserRepository struct {
	mock.Mock
}

// GetAdminUserByUsername provides a mock function with given fields: username, _a1
func (_m *UserRepository) GetAdminUserByUsername(username string, _a1 *user.User) error {
	ret := _m.Called(username, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *user.User) error); ok {
		r0 = rf(username, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEvenBlockedUserByEmail provides a mock function with given fields: email, _a1
func (_m *UserRepository) GetEvenBlockedUserByEmail(email string, _a1 *user.User) error {
	ret := _m.Called(email, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *user.User) error); ok {
		r0 = rf(email, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByID provides a mock function with given fields: ID, _a1
func (_m *UserRepository) GetUserByID(ID int, _a1 *user.User) error {
	ret := _m.Called(ID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *user.User) error); ok {
		r0 = rf(ID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByIDUsingTx provides a mock function with given fields: tx, ID, _a2
func (_m *UserRepository) GetUserByIDUsingTx(tx *gorm.DB, ID int, _a2 *user.User) error {
	ret := _m.Called(tx, ID, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, *user.User) error); ok {
		r0 = rf(tx, ID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByRefreshToken provides a mock function with given fields: refreshToken, _a1
func (_m *UserRepository) GetUserByRefreshToken(refreshToken string, _a1 *user.User) error {
	ret := _m.Called(refreshToken, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *user.User) error); ok {
		r0 = rf(refreshToken, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByUsername provides a mock function with given fields: username, _a1
func (_m *UserRepository) GetUserByUsername(username string, _a1 *user.User) error {
	ret := _m.Called(username, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *user.User) error); ok {
		r0 = rf(username, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByVerificationCode provides a mock function with given fields: code, u
func (_m *UserRepository) GetUserByVerificationCode(code string, u *user.User) error {
	ret := _m.Called(code, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *user.User) error); ok {
		r0 = rf(code, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUsersByPagination provides a mock function with given fields: page, pageSize, filters
func (_m *UserRepository) GetUsersByPagination(page int64, pageSize int, filters map[string]interface{}) []user.User {
	ret := _m.Called(page, pageSize, filters)

	var r0 []user.User
	if rf, ok := ret.Get(0).(func(int64, int, map[string]interface{}) []user.User); ok {
		r0 = rf(page, pageSize, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	return r0
}

// GetUsersDataForOrderMatching provides a mock function with given fields: userIds
func (_m *UserRepository) GetUsersDataForOrderMatching(userIds []int) []user.UsersDataForOrderMatching {
	ret := _m.Called(userIds)

	var r0 []user.UsersDataForOrderMatching
	if rf, ok := ret.Get(0).(func([]int) []user.UsersDataForOrderMatching); ok {
		r0 = rf(userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UsersDataForOrderMatching)
		}
	}

	return r0
}
