// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserPermissionRepository is an autogenerated mock type for the PermissionRepository type
type UserPermissionRepository struct {
	mock.Mock
}

// GetAllPermissions provides a mock function with given fields:
func (_m *UserPermissionRepository) GetAllPermissions() []user.Permission {
	ret := _m.Called()

	var r0 []user.Permission
	if rf, ok := ret.Get(0).(func() []user.Permission); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Permission)
		}
	}

	return r0
}
