// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	mock "github.com/stretchr/testify/mock"

	response "exchange-go/internal/response"

	user "exchange-go/internal/user"

	userwithdrawaddress "exchange-go/internal/userwithdrawaddress"
)

// UserWithdrawAddressService is an autogenerated mock type for the Service type
type UserWithdrawAddressService struct {
	mock.Mock
}

// AddToFavorites provides a mock function with given fields: _a0, params
func (_m *UserWithdrawAddressService) AddToFavorites(_a0 *user.User, params userwithdrawaddress.AddToFavoritesParams) (response.APIResponse, int) {
	ret := _m.Called(_a0, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userwithdrawaddress.AddToFavoritesParams) response.APIResponse); ok {
		r0 = rf(_a0, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userwithdrawaddress.AddToFavoritesParams) int); ok {
		r1 = rf(_a0, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// CreateNewAddress provides a mock function with given fields: _a0, params
func (_m *UserWithdrawAddressService) CreateNewAddress(_a0 *user.User, params userwithdrawaddress.CreateAddressParams) (response.APIResponse, int) {
	ret := _m.Called(_a0, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userwithdrawaddress.CreateAddressParams) response.APIResponse); ok {
		r0 = rf(_a0, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userwithdrawaddress.CreateAddressParams) int); ok {
		r1 = rf(_a0, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, params
func (_m *UserWithdrawAddressService) Delete(_a0 *user.User, params userwithdrawaddress.DeleteParams) (response.APIResponse, int) {
	ret := _m.Called(_a0, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userwithdrawaddress.DeleteParams) response.APIResponse); ok {
		r0 = rf(_a0, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userwithdrawaddress.DeleteParams) int); ok {
		r1 = rf(_a0, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetFormerAddresses provides a mock function with given fields: _a0, params
func (_m *UserWithdrawAddressService) GetFormerAddresses(_a0 *user.User, params userwithdrawaddress.GetFormerAddressesParams) (response.APIResponse, int) {
	ret := _m.Called(_a0, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userwithdrawaddress.GetFormerAddressesParams) response.APIResponse); ok {
		r0 = rf(_a0, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userwithdrawaddress.GetFormerAddressesParams) int); ok {
		r1 = rf(_a0, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetUserWithdrawAddressesByAddress provides a mock function with given fields: _a0, coin, address
func (_m *UserWithdrawAddressService) GetUserWithdrawAddressesByAddress(_a0 *user.User, coin currency.Coin, address string) []userwithdrawaddress.UserWithdrawAddress {
	ret := _m.Called(_a0, coin, address)

	var r0 []userwithdrawaddress.UserWithdrawAddress
	if rf, ok := ret.Get(0).(func(*user.User, currency.Coin, string) []userwithdrawaddress.UserWithdrawAddress); ok {
		r0 = rf(_a0, coin, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userwithdrawaddress.UserWithdrawAddress)
		}
	}

	return r0
}

// GetWithdrawAddresses provides a mock function with given fields: _a0, params
func (_m *UserWithdrawAddressService) GetWithdrawAddresses(_a0 *user.User, params userwithdrawaddress.GetWithdrawAddressesParams) (response.APIResponse, int) {
	ret := _m.Called(_a0, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userwithdrawaddress.GetWithdrawAddressesParams) response.APIResponse); ok {
		r0 = rf(_a0, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userwithdrawaddress.GetWithdrawAddressesParams) int); ok {
		r1 = rf(_a0, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// SaveNewAddress provides a mock function with given fields: _a0, coin, params
func (_m *UserWithdrawAddressService) SaveNewAddress(_a0 *user.User, coin currency.Coin, params userwithdrawaddress.CreateAddressParams) (userwithdrawaddress.UserWithdrawAddress, error) {
	ret := _m.Called(_a0, coin, params)

	var r0 userwithdrawaddress.UserWithdrawAddress
	if rf, ok := ret.Get(0).(func(*user.User, currency.Coin, userwithdrawaddress.CreateAddressParams) userwithdrawaddress.UserWithdrawAddress); ok {
		r0 = rf(_a0, coin, params)
	} else {
		r0 = ret.Get(0).(userwithdrawaddress.UserWithdrawAddress)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*user.User, currency.Coin, userwithdrawaddress.CreateAddressParams) error); ok {
		r1 = rf(_a0, coin, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
