// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	userbalance "exchange-go/internal/userbalance"

	mock "github.com/stretchr/testify/mock"
)

// UserWalletBalanceRepository is an autogenerated mock type for the UserWalletBalanceRepository type
type UserWalletBalanceRepository struct {
	mock.Mock
}

// FindUserWalletBalance provides a mock function with given fields: userId, currencyId, networkCurrencyId, userBalance
func (_m *UserWalletBalanceRepository) FindUserWalletBalance(userId int, currencyId int64, networkCurrencyId int64, userBalance *userbalance.UserWalletBalance) error {
	ret := _m.Called(userId, currencyId, networkCurrencyId, userBalance)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int64, int64, *userbalance.UserWalletBalance) error); ok {
		r0 = rf(userId, currencyId, networkCurrencyId, userBalance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
