// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserLevelRepository is an autogenerated mock type for the LevelRepository type
type UserLevelRepository struct {
	mock.Mock
}

// GetAllLevels provides a mock function with given fields:
func (_m *UserLevelRepository) GetAllLevels() []user.Level {
	ret := _m.Called()

	var r0 []user.Level
	if rf, ok := ret.Get(0).(func() []user.Level); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Level)
		}
	}

	return r0
}

// GetLevelByCode provides a mock function with given fields: code, level
func (_m *UserLevelRepository) GetLevelByCode(code int64, level *user.Level) error {
	ret := _m.Called(code, level)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *user.Level) error); ok {
		r0 = rf(code, level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLevelByID provides a mock function with given fields: id, level
func (_m *UserLevelRepository) GetLevelByID(id int64, level *user.Level) error {
	ret := _m.Called(id, level)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *user.Level) error); ok {
		r0 = rf(id, level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLevelsByIds provides a mock function with given fields: ids
func (_m *UserLevelRepository) GetLevelsByIds(ids []int64) []user.Level {
	ret := _m.Called(ids)

	var r0 []user.Level
	if rf, ok := ret.Get(0).(func([]int64) []user.Level); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Level)
		}
	}

	return r0
}
