// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UsersPermissionsRepository is an autogenerated mock type for the UsersPermissionsRepository type
type UsersPermissionsRepository struct {
	mock.Mock
}

// GetUserPermissions provides a mock function with given fields: userId
func (_m *UsersPermissionsRepository) GetUserPermissions(userId int) []user.UsersPermissions {
	ret := _m.Called(userId)

	var r0 []user.UsersPermissions
	if rf, ok := ret.Get(0).(func(int) []user.UsersPermissions); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UsersPermissions)
		}
	}

	return r0
}
