// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserConfigService is an autogenerated mock type for the ConfigService type
type UserConfigService struct {
	mock.Mock
}

// GetUserConfig provides a mock function with given fields: userID
func (_m *UserConfigService) GetUserConfig(userID int) (user.Config, error) {
	ret := _m.Called(userID)

	var r0 user.Config
	if rf, ok := ret.Get(0).(func(int) user.Config); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(user.Config)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
