// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// UserProfileRepository is an autogenerated mock type for the ProfileRepository type
type UserProfileRepository struct {
	mock.Mock
}

// GetProfileByUserID provides a mock function with given fields: userID, profile
func (_m *UserProfileRepository) GetProfileByUserID(userID int, profile *user.Profile) error {
	ret := _m.Called(userID, profile)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *user.Profile) error); ok {
		r0 = rf(userID, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProfileByUserIDUsingTx provides a mock function with given fields: tx, userId, profile
func (_m *UserProfileRepository) GetProfileByUserIDUsingTx(tx *gorm.DB, userId int, profile *user.Profile) error {
	ret := _m.Called(tx, userId, profile)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, *user.Profile) error); ok {
		r0 = rf(tx, userId, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
