// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserPermissionManager is an autogenerated mock type for the PermissionManager type
type UserPermissionManager struct {
	mock.Mock
}

// GetAllPermissions provides a mock function with given fields:
func (_m *UserPermissionManager) GetAllPermissions() []user.Permission {
	ret := _m.Called()

	var r0 []user.Permission
	if rf, ok := ret.Get(0).(func() []user.Permission); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Permission)
		}
	}

	return r0
}

// IsPermissionGrantedToUserFor provides a mock function with given fields: _a0, permissionName
func (_m *UserPermissionManager) IsPermissionGrantedToUserFor(_a0 user.User, permissionName string) bool {
	ret := _m.Called(_a0, permissionName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.User, string) bool); ok {
		r0 = rf(_a0, permissionName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
