// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	currency "exchange-go/internal/currency"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	response "exchange-go/internal/response"

	user "exchange-go/internal/user"

	userbalance "exchange-go/internal/userbalance"
)

// UserBalanceService is an autogenerated mock type for the Service type
type UserBalanceService struct {
	mock.Mock
}

// GenerateAddress provides a mock function with given fields: ub, u, coin
func (_m *UserBalanceService) GenerateAddress(ub userbalance.UserBalance, u user.User, coin currency.Coin) (string, error) {
	ret := _m.Called(ub, u, coin)

	var r0 string
	if rf, ok := ret.Get(0).(func(userbalance.UserBalance, user.User, currency.Coin) string); ok {
		r0 = rf(ub, u, coin)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(userbalance.UserBalance, user.User, currency.Coin) error); ok {
		r1 = rf(ub, u, coin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateBalancesAndAddressForUser provides a mock function with given fields: u
func (_m *UserBalanceService) GenerateBalancesAndAddressForUser(u user.User) {
	_m.Called(u)
}

// GenerateSingleUserBalanceForCoin provides a mock function with given fields: u, coin
func (_m *UserBalanceService) GenerateSingleUserBalanceForCoin(u user.User, coin currency.Coin) (userbalance.UserBalance, error) {
	ret := _m.Called(u, coin)

	var r0 userbalance.UserBalance
	if rf, ok := ret.Get(0).(func(user.User, currency.Coin) userbalance.UserBalance); ok {
		r0 = rf(u, coin)
	} else {
		r0 = ret.Get(0).(userbalance.UserBalance)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.User, currency.Coin) error); ok {
		r1 = rf(u, coin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllBalances provides a mock function with given fields: u, params
func (_m *UserBalanceService) GetAllBalances(u *user.User, params userbalance.GetAllBalancesParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userbalance.GetAllBalancesParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userbalance.GetAllBalancesParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetBalanceOfUserByCoinID provides a mock function with given fields: userID, coinID, balance
func (_m *UserBalanceService) GetBalanceOfUserByCoinID(userID int, coinID int64, balance *userbalance.UserBalance) error {
	ret := _m.Called(userID, coinID, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int64, *userbalance.UserBalance) error); ok {
		r0 = rf(userID, coinID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalanceOfUserByCoinUsingTx provides a mock function with given fields: tx, userID, coinID, balance
func (_m *UserBalanceService) GetBalanceOfUserByCoinUsingTx(tx *gorm.DB, userID int, coinID int64, balance *userbalance.UserBalance) error {
	ret := _m.Called(tx, userID, coinID, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int, int64, *userbalance.UserBalance) error); ok {
		r0 = rf(tx, userID, coinID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalancesOfUsersForCoins provides a mock function with given fields: userIds, coinIds
func (_m *UserBalanceService) GetBalancesOfUsersForCoins(userIds []int, coinIds []int64) []userbalance.UserBalance {
	ret := _m.Called(userIds, coinIds)

	var r0 []userbalance.UserBalance
	if rf, ok := ret.Get(0).(func([]int, []int64) []userbalance.UserBalance); ok {
		r0 = rf(userIds, coinIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userbalance.UserBalance)
		}
	}

	return r0
}

// GetBalancesOfUsersForCoinsUsingTx provides a mock function with given fields: tx, userIds, coinIds
func (_m *UserBalanceService) GetBalancesOfUsersForCoinsUsingTx(tx *gorm.DB, userIds []int, coinIds []int64) []userbalance.UserBalance {
	ret := _m.Called(tx, userIds, coinIds)

	var r0 []userbalance.UserBalance
	if rf, ok := ret.Get(0).(func(*gorm.DB, []int, []int64) []userbalance.UserBalance); ok {
		r0 = rf(tx, userIds, coinIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userbalance.UserBalance)
		}
	}

	return r0
}

// GetPairBalances provides a mock function with given fields: u, params
func (_m *UserBalanceService) GetPairBalances(u *user.User, params userbalance.GetPairBalancesParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userbalance.GetPairBalancesParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userbalance.GetPairBalancesParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetUserBalanceByCoinAndAddressUsingTx provides a mock function with given fields: tx, coinID, address, ub
func (_m *UserBalanceService) GetUserBalanceByCoinAndAddressUsingTx(tx *gorm.DB, coinID int64, address string, ub *userbalance.UserBalance) error {
	ret := _m.Called(tx, coinID, address, ub)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, int64, string, *userbalance.UserBalance) error); ok {
		r0 = rf(tx, coinID, address, ub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWithdrawDepositData provides a mock function with given fields: u, params
func (_m *UserBalanceService) GetWithdrawDepositData(u *user.User, params userbalance.GetWithdrawDepositParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userbalance.GetWithdrawDepositParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userbalance.GetWithdrawDepositParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// SetAutoExchangeCoin provides a mock function with given fields: u, params
func (_m *UserBalanceService) SetAutoExchangeCoin(u *user.User, params userbalance.SetAutoExchangeCoinParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userbalance.SetAutoExchangeCoinParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userbalance.SetAutoExchangeCoinParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// UpdateUserBalanceFromAdmin provides a mock function with given fields: u, params
func (_m *UserBalanceService) UpdateUserBalanceFromAdmin(u *user.User, params userbalance.UpdateUserBalanceFromAdminParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, userbalance.UpdateUserBalanceFromAdminParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, userbalance.UpdateUserBalanceFromAdminParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// UpsertUserWalletBalance provides a mock function with given fields: params
func (_m *UserBalanceService) UpsertUserWalletBalance(params userbalance.UpsertUserWalletBalancesParams) error {
	ret := _m.Called(params)

	var r0 error
	if rf, ok := ret.Get(0).(func(userbalance.UpsertUserWalletBalancesParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
