// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "exchange-go/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserConfigRepository is an autogenerated mock type for the ConfigRepository type
type UserConfigRepository struct {
	mock.Mock
}

// GetUserConfigByUserID provides a mock function with given fields: userID, config
func (_m *UserConfigRepository) GetUserConfigByUserID(userID int, config *user.Config) error {
	ret := _m.Called(userID, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *user.Config) error); ok {
		r0 = rf(userID, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
