// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	response "exchange-go/internal/response"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	user "exchange-go/internal/user"
)

// UserService is an autogenerated mock type for the Service type
type UserService struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: u, params
func (_m *UserService) ChangePassword(u *user.User, params user.ChangePasswordParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.ChangePasswordParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.ChangePasswordParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// DeleteImage provides a mock function with given fields: u, params
func (_m *UserService) DeleteImage(u *user.User, params user.DeleteImageParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.DeleteImageParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.DeleteImageParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// Disable2Fa provides a mock function with given fields: u, params
func (_m *UserService) Disable2Fa(u *user.User, params user.Disable2FaParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.Disable2FaParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.Disable2FaParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// DisableSms provides a mock function with given fields: u, params
func (_m *UserService) DisableSms(u *user.User, params user.DisableSmsParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.DisableSmsParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.DisableSmsParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// Enable2Fa provides a mock function with given fields: u, params
func (_m *UserService) Enable2Fa(u *user.User, params user.Enable2FaParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.Enable2FaParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.Enable2FaParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// EnableSms provides a mock function with given fields: u, params
func (_m *UserService) EnableSms(u *user.User, params user.EnableSmsParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.EnableSmsParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.EnableSmsParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// Get2FaBarcode provides a mock function with given fields: u
func (_m *UserService) Get2FaBarcode(u *user.User) (response.APIResponse, int) {
	ret := _m.Called(u)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User) response.APIResponse); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User) int); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetProfile provides a mock function with given fields: u
func (_m *UserService) GetProfile(u *user.User) (response.APIResponse, int) {
	ret := _m.Called(u)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User) response.APIResponse); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User) int); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ID
func (_m *UserService) GetUserByID(ID int) (user.User, error) {
	ret := _m.Called(ID)

	var r0 user.User
	if rf, ok := ret.Get(0).(func(int) user.User); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserData provides a mock function with given fields: u
func (_m *UserService) GetUserData(u *user.User) (response.APIResponse, int) {
	ret := _m.Called(u)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User) response.APIResponse); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User) int); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// GetUserProfile provides a mock function with given fields: u
func (_m *UserService) GetUserProfile(u user.User) (user.Profile, error) {
	ret := _m.Called(u)

	var r0 user.Profile
	if rf, ok := ret.Get(0).(func(user.User) user.Profile); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(user.Profile)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.User) error); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfileUsingTx provides a mock function with given fields: tx, u
func (_m *UserService) GetUserProfileUsingTx(tx *gorm.DB, u user.User) (user.Profile, error) {
	ret := _m.Called(tx, u)

	var r0 user.Profile
	if rf, ok := ret.Get(0).(func(*gorm.DB, user.User) user.Profile); ok {
		r0 = rf(tx, u)
	} else {
		r0 = ret.Get(0).(user.Profile)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, user.User) error); ok {
		r1 = rf(tx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByPagination provides a mock function with given fields: page, pageSize, filters
func (_m *UserService) GetUsersByPagination(page int64, pageSize int, filters map[string]interface{}) []user.User {
	ret := _m.Called(page, pageSize, filters)

	var r0 []user.User
	if rf, ok := ret.Get(0).(func(int64, int, map[string]interface{}) []user.User); ok {
		r0 = rf(page, pageSize, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	return r0
}

// GetUsersDataForOrderMatching provides a mock function with given fields: userIds
func (_m *UserService) GetUsersDataForOrderMatching(userIds []int) []user.UsersDataForOrderMatching {
	ret := _m.Called(userIds)

	var r0 []user.UsersDataForOrderMatching
	if rf, ok := ret.Get(0).(func([]int) []user.UsersDataForOrderMatching); ok {
		r0 = rf(userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UsersDataForOrderMatching)
		}
	}

	return r0
}

// SendSms provides a mock function with given fields: u, params
func (_m *UserService) SendSms(u *user.User, params user.SendSmsParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.SendSmsParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.SendSmsParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// SendVerificationEmail provides a mock function with given fields: u
func (_m *UserService) SendVerificationEmail(u *user.User) (response.APIResponse, int) {
	ret := _m.Called(u)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User) response.APIResponse); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User) int); ok {
		r1 = rf(u)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// SetUserProfile provides a mock function with given fields: u, params
func (_m *UserService) SetUserProfile(u *user.User, params user.SetUserProfileParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.SetUserProfileParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.SetUserProfileParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// UploadImages provides a mock function with given fields: u, params
func (_m *UserService) UploadImages(u *user.User, params user.UploadImagesParams) (response.APIResponse, int) {
	ret := _m.Called(u, params)

	var r0 response.APIResponse
	if rf, ok := ret.Get(0).(func(*user.User, user.UploadImagesParams) response.APIResponse); ok {
		r0 = rf(u, params)
	} else {
		r0 = ret.Get(0).(response.APIResponse)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(*user.User, user.UploadImagesParams) int); ok {
		r1 = rf(u, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}
