// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WalletService is an autogenerated mock type for the Service type
type WalletService struct {
	mock.Mock
}

// GetAddressBalance provides a mock function with given fields: code, network, address, isHumanReadable
func (_m *WalletService) GetAddressBalance(code string, network string, address string, isHumanReadable bool) (string, error) {
	ret := _m.Called(code, network, address, isHumanReadable)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string, bool) string); ok {
		r0 = rf(code, network, address, isHumanReadable)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, bool) error); ok {
		r1 = rf(code, network, address, isHumanReadable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAddressForUser provides a mock function with given fields: coin, userCode
func (_m *WalletService) GetAddressForUser(coin string, userCode string) (string, error) {
	ret := _m.Called(coin, userCode)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(coin, userCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(coin, userCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsAddressValid provides a mock function with given fields: coin, address, network
func (_m *WalletService) IsAddressValid(coin string, address string, network string) (bool, error) {
	ret := _m.Called(coin, address, network)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(coin, address, network)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(coin, address, network)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendTransaction provides a mock function with given fields: coin, amount, toAddress, network, networkFee
func (_m *WalletService) SendTransaction(coin string, amount string, toAddress string, network string, networkFee string) (string, error) {
	ret := _m.Called(coin, amount, toAddress, network, networkFee)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) string); ok {
		r0 = rf(coin, amount, toAddress, network, networkFee)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(coin, amount, toAddress, network, networkFee)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
