// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	user "exchange-go/internal/user"
)

// WithdrawEmailConfirmationManager is an autogenerated mock type for the WithdrawEmailConfirmationManager type
type WithdrawEmailConfirmationManager struct {
	mock.Mock
}

// CheckCode provides a mock function with given fields: u, code
func (_m *WithdrawEmailConfirmationManager) CheckCode(u user.User, code string) (bool, error) {
	ret := _m.Called(u, code)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.User, string) bool); ok {
		r0 = rf(u, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.User, string) error); ok {
		r1 = rf(u, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAndSendWithdrawEmailConfirmationCode provides a mock function with given fields: u, coin, amount, address
func (_m *WithdrawEmailConfirmationManager) CreateAndSendWithdrawEmailConfirmationCode(u user.User, coin string, amount string, address string) error {
	ret := _m.Called(u, coin, amount, address)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.User, string, string, string) error); ok {
		r0 = rf(u, coin, amount, address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsAllowedToSendEmail provides a mock function with given fields: u, coin, amount, address
func (_m *WithdrawEmailConfirmationManager) IsAllowedToSendEmail(u user.User, coin string, amount string, address string) (bool, error) {
	ret := _m.Called(u, coin, amount, address)

	var r0 bool
	if rf, ok := ret.Get(0).(func(user.User, string, string, string) bool); ok {
		r0 = rf(u, coin, amount, address)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.User, string, string, string) error); ok {
		r1 = rf(u, coin, amount, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveConfirmationCodeFromRedis provides a mock function with given fields: u, coin, amount, address
func (_m *WithdrawEmailConfirmationManager) RemoveConfirmationCodeFromRedis(u user.User, coin string, amount string, address string) error {
	ret := _m.Called(u, coin, amount, address)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.User, string, string, string) error); ok {
		r0 = rf(u, coin, amount, address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
