// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package candle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CandlePriceClient is the client API for CandlePrice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CandlePriceClient interface {
	GetLastCandle(ctx context.Context, in *LastCandleRequest, opts ...grpc.CallOption) (*LastCandleReply, error)
	GetAveragePriceOfPairs(ctx context.Context, in *AveragePriceOfPairsRequest, opts ...grpc.CallOption) (*AveragePriceOfPairsReply, error)
	GetHighAndLowPriceOfPairFromDate(ctx context.Context, in *HighAndLowRequest, opts ...grpc.CallOption) (*HighAndLowReply, error)
	GetCandles(ctx context.Context, in *GetCandlesRequest, opts ...grpc.CallOption) (*GetCandlesReply, error)
}

type candlePriceClient struct {
	cc grpc.ClientConnInterface
}

func NewCandlePriceClient(cc grpc.ClientConnInterface) CandlePriceClient {
	return &candlePriceClient{cc}
}

func (c *candlePriceClient) GetLastCandle(ctx context.Context, in *LastCandleRequest, opts ...grpc.CallOption) (*LastCandleReply, error) {
	out := new(LastCandleReply)
	err := c.cc.Invoke(ctx, "/CandlePrice/GetLastCandle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candlePriceClient) GetAveragePriceOfPairs(ctx context.Context, in *AveragePriceOfPairsRequest, opts ...grpc.CallOption) (*AveragePriceOfPairsReply, error) {
	out := new(AveragePriceOfPairsReply)
	err := c.cc.Invoke(ctx, "/CandlePrice/GetAveragePriceOfPairs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candlePriceClient) GetHighAndLowPriceOfPairFromDate(ctx context.Context, in *HighAndLowRequest, opts ...grpc.CallOption) (*HighAndLowReply, error) {
	out := new(HighAndLowReply)
	err := c.cc.Invoke(ctx, "/CandlePrice/GetHighAndLowPriceOfPairFromDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candlePriceClient) GetCandles(ctx context.Context, in *GetCandlesRequest, opts ...grpc.CallOption) (*GetCandlesReply, error) {
	out := new(GetCandlesReply)
	err := c.cc.Invoke(ctx, "/CandlePrice/GetCandles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandlePriceServer is the server API for CandlePrice service.
// All implementations must embed UnimplementedCandlePriceServer
// for forward compatibility
type CandlePriceServer interface {
	GetLastCandle(context.Context, *LastCandleRequest) (*LastCandleReply, error)
	GetAveragePriceOfPairs(context.Context, *AveragePriceOfPairsRequest) (*AveragePriceOfPairsReply, error)
	GetHighAndLowPriceOfPairFromDate(context.Context, *HighAndLowRequest) (*HighAndLowReply, error)
	GetCandles(context.Context, *GetCandlesRequest) (*GetCandlesReply, error)
	mustEmbedUnimplementedCandlePriceServer()
}

// UnimplementedCandlePriceServer must be embedded to have forward compatible implementations.
type UnimplementedCandlePriceServer struct {
}

func (UnimplementedCandlePriceServer) GetLastCandle(context.Context, *LastCandleRequest) (*LastCandleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastCandle not implemented")
}
func (UnimplementedCandlePriceServer) GetAveragePriceOfPairs(context.Context, *AveragePriceOfPairsRequest) (*AveragePriceOfPairsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAveragePriceOfPairs not implemented")
}
func (UnimplementedCandlePriceServer) GetHighAndLowPriceOfPairFromDate(context.Context, *HighAndLowRequest) (*HighAndLowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHighAndLowPriceOfPairFromDate not implemented")
}
func (UnimplementedCandlePriceServer) GetCandles(context.Context, *GetCandlesRequest) (*GetCandlesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCandles not implemented")
}
func (UnimplementedCandlePriceServer) mustEmbedUnimplementedCandlePriceServer() {}

// UnsafeCandlePriceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandlePriceServer will
// result in compilation errors.
type UnsafeCandlePriceServer interface {
	mustEmbedUnimplementedCandlePriceServer()
}

func RegisterCandlePriceServer(s grpc.ServiceRegistrar, srv CandlePriceServer) {
	s.RegisterService(&CandlePrice_ServiceDesc, srv)
}

func _CandlePrice_GetLastCandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastCandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandlePriceServer).GetLastCandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CandlePrice/GetLastCandle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandlePriceServer).GetLastCandle(ctx, req.(*LastCandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandlePrice_GetAveragePriceOfPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AveragePriceOfPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandlePriceServer).GetAveragePriceOfPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CandlePrice/GetAveragePriceOfPairs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandlePriceServer).GetAveragePriceOfPairs(ctx, req.(*AveragePriceOfPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandlePrice_GetHighAndLowPriceOfPairFromDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HighAndLowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandlePriceServer).GetHighAndLowPriceOfPairFromDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CandlePrice/GetHighAndLowPriceOfPairFromDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandlePriceServer).GetHighAndLowPriceOfPairFromDate(ctx, req.(*HighAndLowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandlePrice_GetCandles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandlePriceServer).GetCandles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CandlePrice/GetCandles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandlePriceServer).GetCandles(ctx, req.(*GetCandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CandlePrice_ServiceDesc is the grpc.ServiceDesc for CandlePrice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandlePrice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CandlePrice",
	HandlerType: (*CandlePriceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastCandle",
			Handler:    _CandlePrice_GetLastCandle_Handler,
		},
		{
			MethodName: "GetAveragePriceOfPairs",
			Handler:    _CandlePrice_GetAveragePriceOfPairs_Handler,
		},
		{
			MethodName: "GetHighAndLowPriceOfPairFromDate",
			Handler:    _CandlePrice_GetHighAndLowPriceOfPairFromDate_Handler,
		},
		{
			MethodName: "GetCandles",
			Handler:    _CandlePrice_GetCandles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "candle.proto",
}
