// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: candle.proto

package candle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LastCandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair      string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *LastCandleRequest) Reset() {
	*x = LastCandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastCandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastCandleRequest) ProtoMessage() {}

func (x *LastCandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastCandleRequest.ProtoReflect.Descriptor instead.
func (*LastCandleRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{0}
}

func (x *LastCandleRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *LastCandleRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LastCandleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Open  string `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	High  string `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	Close string `protobuf:"bytes,3,opt,name=close,proto3" json:"close,omitempty"`
	Low   string `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
}

func (x *LastCandleReply) Reset() {
	*x = LastCandleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastCandleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastCandleReply) ProtoMessage() {}

func (x *LastCandleReply) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastCandleReply.ProtoReflect.Descriptor instead.
func (*LastCandleReply) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{1}
}

func (x *LastCandleReply) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *LastCandleReply) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *LastCandleReply) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *LastCandleReply) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

type AveragePriceOfPairsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs    []string `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	FromTime int64    `protobuf:"varint,2,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	ToTime   int64    `protobuf:"varint,3,opt,name=ToTime,proto3" json:"ToTime,omitempty"`
}

func (x *AveragePriceOfPairsRequest) Reset() {
	*x = AveragePriceOfPairsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AveragePriceOfPairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AveragePriceOfPairsRequest) ProtoMessage() {}

func (x *AveragePriceOfPairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AveragePriceOfPairsRequest.ProtoReflect.Descriptor instead.
func (*AveragePriceOfPairsRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{2}
}

func (x *AveragePriceOfPairsRequest) GetPairs() []string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *AveragePriceOfPairsRequest) GetFromTime() int64 {
	if x != nil {
		return x.FromTime
	}
	return 0
}

func (x *AveragePriceOfPairsRequest) GetToTime() int64 {
	if x != nil {
		return x.ToTime
	}
	return 0
}

type AveragePriceOfPairsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AveragePrices []*AveragePriceOfPairsReply_AveragePrice `protobuf:"bytes,1,rep,name=averagePrices,proto3" json:"averagePrices,omitempty"`
}

func (x *AveragePriceOfPairsReply) Reset() {
	*x = AveragePriceOfPairsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AveragePriceOfPairsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AveragePriceOfPairsReply) ProtoMessage() {}

func (x *AveragePriceOfPairsReply) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AveragePriceOfPairsReply.ProtoReflect.Descriptor instead.
func (*AveragePriceOfPairsReply) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{3}
}

func (x *AveragePriceOfPairsReply) GetAveragePrices() []*AveragePriceOfPairsReply_AveragePrice {
	if x != nil {
		return x.AveragePrices
	}
	return nil
}

type HighAndLowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair      string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HighAndLowRequest) Reset() {
	*x = HighAndLowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HighAndLowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighAndLowRequest) ProtoMessage() {}

func (x *HighAndLowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighAndLowRequest.ProtoReflect.Descriptor instead.
func (*HighAndLowRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{4}
}

func (x *HighAndLowRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *HighAndLowRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HighAndLowReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	High string `protobuf:"bytes,1,opt,name=high,proto3" json:"high,omitempty"`
	Low  string `protobuf:"bytes,2,opt,name=low,proto3" json:"low,omitempty"`
}

func (x *HighAndLowReply) Reset() {
	*x = HighAndLowReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HighAndLowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighAndLowReply) ProtoMessage() {}

func (x *HighAndLowReply) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighAndLowReply.ProtoReflect.Descriptor instead.
func (*HighAndLowReply) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{5}
}

func (x *HighAndLowReply) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *HighAndLowReply) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

type GetCandlesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs     []string `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	TimeFrame string   `protobuf:"bytes,2,opt,name=timeFrame,proto3" json:"timeFrame,omitempty"`
	FromTime  int64    `protobuf:"varint,3,opt,name=fromTime,proto3" json:"fromTime,omitempty"`
	ToTime    int64    `protobuf:"varint,4,opt,name=toTime,proto3" json:"toTime,omitempty"`
}

func (x *GetCandlesRequest) Reset() {
	*x = GetCandlesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesRequest) ProtoMessage() {}

func (x *GetCandlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesRequest.ProtoReflect.Descriptor instead.
func (*GetCandlesRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{6}
}

func (x *GetCandlesRequest) GetPairs() []string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *GetCandlesRequest) GetTimeFrame() string {
	if x != nil {
		return x.TimeFrame
	}
	return ""
}

func (x *GetCandlesRequest) GetFromTime() int64 {
	if x != nil {
		return x.FromTime
	}
	return 0
}

func (x *GetCandlesRequest) GetToTime() int64 {
	if x != nil {
		return x.ToTime
	}
	return 0
}

type GetCandlesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candles []*GetCandlesReply_Candle `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
}

func (x *GetCandlesReply) Reset() {
	*x = GetCandlesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandlesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesReply) ProtoMessage() {}

func (x *GetCandlesReply) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesReply.ProtoReflect.Descriptor instead.
func (*GetCandlesReply) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{7}
}

func (x *GetCandlesReply) GetCandles() []*GetCandlesReply_Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

type AveragePriceOfPairsReply_AveragePrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair  string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Day   string `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	Price string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *AveragePriceOfPairsReply_AveragePrice) Reset() {
	*x = AveragePriceOfPairsReply_AveragePrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AveragePriceOfPairsReply_AveragePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AveragePriceOfPairsReply_AveragePrice) ProtoMessage() {}

func (x *AveragePriceOfPairsReply_AveragePrice) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AveragePriceOfPairsReply_AveragePrice.ProtoReflect.Descriptor instead.
func (*AveragePriceOfPairsReply_AveragePrice) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AveragePriceOfPairsReply_AveragePrice) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *AveragePriceOfPairsReply_AveragePrice) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *AveragePriceOfPairsReply_AveragePrice) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type GetCandlesReply_Candle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair      string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price     string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	StartTime string `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *GetCandlesReply_Candle) Reset() {
	*x = GetCandlesReply_Candle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_candle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandlesReply_Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesReply_Candle) ProtoMessage() {}

func (x *GetCandlesReply_Candle) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesReply_Candle.ProtoReflect.Descriptor instead.
func (*GetCandlesReply_Candle) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetCandlesReply_Candle) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetCandlesReply_Candle) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetCandlesReply_Candle) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetCandlesReply_Candle) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

var File_candle_proto protoreflect.FileDescriptor

var file_candle_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45,
	0x0a, 0x11, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x61, 0x0a, 0x0f, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x22, 0x66, 0x0a, 0x1a, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x66, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x6f, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0xb4, 0x01, 0x0a, 0x18, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x4f, 0x66, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a,
	0x0d, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4f, 0x66, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x0d, 0x61, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x4a, 0x0a, 0x0c, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x45, 0x0a, 0x11, 0x48, 0x69, 0x67, 0x68, 0x41,
	0x6e, 0x64, 0x4c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x37,
	0x0a, 0x0f, 0x48, 0x69, 0x67, 0x68, 0x41, 0x6e, 0x64, 0x4c, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x22, 0x7b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x69,
	0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x6f,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x1a, 0x6a, 0x0a, 0x06, 0x43,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x9c, 0x02, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x43,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x4c,
	0x61, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x52, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x4f, 0x66, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x41, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x66, 0x50, 0x61, 0x69, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x66, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x48, 0x69, 0x67, 0x68, 0x41,
	0x6e, 0x64, 0x4c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x66, 0x50, 0x61, 0x69, 0x72,
	0x46, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x48, 0x69, 0x67, 0x68, 0x41,
	0x6e, 0x64, 0x4c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x48,
	0x69, 0x67, 0x68, 0x41, 0x6e, 0x64, 0x4c, 0x6f, 0x77, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x12,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x63, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_candle_proto_rawDescOnce sync.Once
	file_candle_proto_rawDescData = file_candle_proto_rawDesc
)

func file_candle_proto_rawDescGZIP() []byte {
	file_candle_proto_rawDescOnce.Do(func() {
		file_candle_proto_rawDescData = protoimpl.X.CompressGZIP(file_candle_proto_rawDescData)
	})
	return file_candle_proto_rawDescData
}

var file_candle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_candle_proto_goTypes = []interface{}{
	(*LastCandleRequest)(nil),                     // 0: LastCandleRequest
	(*LastCandleReply)(nil),                       // 1: LastCandleReply
	(*AveragePriceOfPairsRequest)(nil),            // 2: AveragePriceOfPairsRequest
	(*AveragePriceOfPairsReply)(nil),              // 3: AveragePriceOfPairsReply
	(*HighAndLowRequest)(nil),                     // 4: HighAndLowRequest
	(*HighAndLowReply)(nil),                       // 5: HighAndLowReply
	(*GetCandlesRequest)(nil),                     // 6: GetCandlesRequest
	(*GetCandlesReply)(nil),                       // 7: GetCandlesReply
	(*AveragePriceOfPairsReply_AveragePrice)(nil), // 8: AveragePriceOfPairsReply.AveragePrice
	(*GetCandlesReply_Candle)(nil),                // 9: GetCandlesReply.Candle
}
var file_candle_proto_depIdxs = []int32{
	8, // 0: AveragePriceOfPairsReply.averagePrices:type_name -> AveragePriceOfPairsReply.AveragePrice
	9, // 1: GetCandlesReply.candles:type_name -> GetCandlesReply.Candle
	0, // 2: CandlePrice.GetLastCandle:input_type -> LastCandleRequest
	2, // 3: CandlePrice.GetAveragePriceOfPairs:input_type -> AveragePriceOfPairsRequest
	4, // 4: CandlePrice.GetHighAndLowPriceOfPairFromDate:input_type -> HighAndLowRequest
	6, // 5: CandlePrice.GetCandles:input_type -> GetCandlesRequest
	1, // 6: CandlePrice.GetLastCandle:output_type -> LastCandleReply
	3, // 7: CandlePrice.GetAveragePriceOfPairs:output_type -> AveragePriceOfPairsReply
	5, // 8: CandlePrice.GetHighAndLowPriceOfPairFromDate:output_type -> HighAndLowReply
	7, // 9: CandlePrice.GetCandles:output_type -> GetCandlesReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_candle_proto_init() }
func file_candle_proto_init() {
	if File_candle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_candle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastCandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastCandleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AveragePriceOfPairsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AveragePriceOfPairsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HighAndLowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HighAndLowReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandlesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandlesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AveragePriceOfPairsReply_AveragePrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_candle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandlesReply_Candle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_candle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_candle_proto_goTypes,
		DependencyIndexes: file_candle_proto_depIdxs,
		MessageInfos:      file_candle_proto_msgTypes,
	}.Build()
	File_candle_proto = out.File
	file_candle_proto_rawDesc = nil
	file_candle_proto_goTypes = nil
	file_candle_proto_depIdxs = nil
}
